In [2]:
import pandas as pd


df = pd.read_csv('Car_sales.csv')

df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [3]:
df['Vehicle_type'].value_counts()

Vehicle_type
Passenger    116
Car           41
Name: count, dtype: int64

In [4]:
#selecting columns
df_filter = df[['Manufacturer','Sales_in_thousands','Vehicle_type','Price_in_thousands','Engine_size','Horsepower','Fuel_capacity']]
df_filter

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.50,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.40,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.00,3.5,210.0,18.0
4,Audi,20.397,Passenger,23.99,1.8,150.0,16.4
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.40,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.50,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.80,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.50,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.00,2.9,201.0,21.1

In [5]:
#calculate no of unique values
df_filter.nunique()

Manufacturer           30
Sales_in_thousands    157
Vehicle_type            2
Price_in_thousands    152
Engine_size            31
Horsepower             66
Fuel_capacity          55
dtype: int64

1 agg()

In [6]:
#calculate the sum of cols 
df_filter.agg('sum')

Manufacturer          AcuraAcuraAcuraAcuraAudiAudiAudiBMWBMWBMWBuick...
Sales_in_thousands                                             8320.698
Vehicle_type          PassengerPassengerPassengerPassengerPassengerP...
Price_in_thousands                                             4245.567
Engine_size                                                       477.5
Horsepower                                                      29008.0
Fuel_capacity                                                    2800.5
dtype: object

In [8]:
#calculate the mean of numeric values
df_filter[['Sales_in_thousands','Price_in_thousands','Engine_size']].agg('mean')

Sales_in_thousands    52.998076
Price_in_thousands    27.390755
Engine_size            3.060897
dtype: float64

In [10]:
#cal mean and count values
df_filter[['Sales_in_thousands','Price_in_thousands','Engine_size','Fuel_capacity']].apply(['mean','count'])

       Sales_in_thousands  Price_in_thousands  Engine_size  Fuel_capacity
mean            52.998076           27.390755     3.060897      17.951923
count          157.000000          155.000000   156.000000     156.000000

In [11]:
#different aggregations per col : cal sum and mean of 'Sales_in_thousand' and sum and max for Price_in_thousands


df_filter.agg({'Sales_in_thousands':['sum','mean'],
               'Price_in_thousands':['sum','max'] })

      Sales_in_thousands  Price_in_thousands
sum          8320.698000            4245.567
mean           52.998076                 NaN
max                  NaN              85.500

In [15]:
#aggregate over cols
df_filter[['Sales_in_thousands','Price_in_thousands']].agg('sum',axis=1) #takes null as 0

0      38.419
1      67.784
2      14.114
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

In [16]:
#equivalent (NaN behaves differently)

df_filter['Sales_in_thousands'] + df_filter['Price_in_thousands']

0      38.419
1      67.784
2         NaN
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

In [18]:
#aggregate diff func and rename the index of the resulting dataframe

df_filter.agg( x  = ('Sales_in_thousands','sum'),
               y  = ('Price_in_thousands','sum')  )

   Sales_in_thousands  Price_in_thousands
x            8320.698                 NaN
y                 NaN            4245.567

2 the split-apply combine strategy

In [20]:
#split data into seperate groups

passenger_filter  = df_filter['Vehicle_type']=="Passenger"
car_filter  = df_filter['Vehicle_type']=="Car"

In [24]:
#apply an operation

passsenger_average  = df[passenger_filter]['Sales_in_thousands'].mean()

car_average  = df[car_filter]['Sales_in_thousands'].mean()

In [25]:
#combine results

pd.DataFrame({'Vehicle_type':['Car','Passenger'],
              'Sales_in_thousands' :[car_average , passsenger_average] } )

  Vehicle_type  Sales_in_thousands
0          Car           80.622293
1    Passenger           43.234345

3 groupby()

In [29]:
#group ny vehicle type and calculate mean
# we can't pass now numeric columns and call mean
df_filter[['Sales_in_thousands','Price_in_thousands','Engine_size','Vehicle_type']].groupby('Vehicle_type').mean()

              Sales_in_thousands  Price_in_thousands  Engine_size
Vehicle_type
Car                    80.622293           26.319975     3.520000
Passenger              43.234345           27.763200     2.902586

In [31]:
#group by manufactures 
groupby_obj = df_filter.groupby('Manufacturer')

In [32]:
#the groupby_obj
groupby_obj

In [34]:
#groups attribute and keys
groupby_obj.groups

groupby_obj.groups.keys()

dict_keys(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet', 'Chrysler', 'Dodge', 'Ford', 'Honda', 'Hyundai', 'Infiniti', 'Jaguar', 'Jeep', 'Lexus', 'Lincoln', 'Mercedes-B', 'Mercury', 'Mitsubishi', 'Nissan', 'Oldsmobile', 'Plymouth', 'Pontiac', 'Porsche', 'Saab', 'Saturn', 'Subaru', 'Toyota', 'Volkswagen', 'Volvo'])

In [35]:
#get a specific group within manufacturer col
groupby_obj.get_group('Ford')

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
46,Ford,70.227,Passenger,12.070,2.0,110.0,12.7
47,Ford,113.369,Passenger,21.560,3.8,190.0,15.7
48,Ford,35.068,Passenger,17.035,2.5,170.0,15.0
49,Ford,245.815,Passenger,17.885,3.0,155.0,16.0
50,Ford,175.670,Passenger,12.315,2.0,107.0,13.2
51,Ford,63.403,Passenger,22.195,4.6,200.0,19.0
52,Ford,276.747,Car,31.930,4.0,210.0,21.0
53,Ford,155.787,Car,21.410,3.0,150.0,26.0
54,Ford,125.338,Car,36.135,4.6,240.0,26.0
55,Ford,220.650,Car,12.050,2.5,119.0,20.0
56,Ford,540.561,Car,26.935,4.6,220.0,25.1

In [37]:
#group by manufacturer and cal the sum 

df_filter.groupby('Manufacturer').sum()

,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,,
Acura,79.005,PassengerPassengerPassengerPassenger,91.900,11.7,800.0,65.6
Audi,40.557,PassengerPassengerPassenger,119.940,8.8,660.0,58.6
BMW,46.505,PassengerPassengerPassenger,99.290,8.1,556.0,51.7
Buick,242.019,PassengerPassengerPassengerPassenger,107.125,14.5,825.0,71.0
Cadillac,112.178,PassengerPassengerPassengerPassengerCar,201.270,22.5,1280.0,104.0
Chevrolet,554.365,PassengerPassengerPassengerPassengerPassengerP...,180.205,27.5,1540.0,139.3
Chrysler,201.721,PassengerPassengerPassengerPassengerPassengerC...,140.585,16.7,1169.0,98.9
Dodge,910.149,PassengerPassengerPassengerPassengerPassengerC...,266.350,40.8,2195.0,237.4
Ford,2022.635,PassengerPassengerPassengerPassengerPassengerP...,231.520,36.6,1871.0,209.7
Honda,592.674,PassengerPassengerCarCarCar,101.385,12.6,802.0,85.4
Hyundai,137.326,PassengerPassengerPassenger,36.497,5.9,380.0,43.6
Infiniti,23.713,Passenger,29.465,3.0,227.0,18.5
Jaguar,15.467,Passenger,42.800,3.0,240.0,18.4
Jeep,293.153,CarCarCar,62.975,10.5,505.0,59.5
Lexus,106.843,PassengerPassengerPassengerPassengerCarCar,264.330,21.7,1475.0,123.2
Lincoln,85.634,PassengerPassengerCar,125.070,14.6,790.0,69.0
Mercedes-B,117.125,PassengerPassengerPassengerPassengerPassengerP...,476.250,30.8,2090.0,170.3
Mercury,237.999,PassengerPassengerPassengerPassengerCarCar,124.490,18.9,983.0,107.0
Mitsubishi,180.895,PassengerPassengerPassengerPassengerPassengerC...,155.172,19.6,1156.0,128.0
Nissan,399.635,PassengerPassengerPassengerCarCarCarCar,156.525,20.4,1183.0,127.4
Oldsmobile,178.989,PassengerPassengerPassengerPassengerCarCar,153.737,20.7,1140.0,109.2
Plymouth,64.001,PassengerPassengerCarPassenger,90.570,9.9,667.0,60.5
Pontiac,370.534,PassengerPassengerPassengerPassengerPassengerCar,137.695,20.6,1110.0,107.5
Porsche,12.128,PassengerPassengerPassenger,187.420,9.5,817.0,51.0
Saab,21.306,PassengerPassenger,59.220,4.3,355.0,35.4
Saturn,168.850,PassengerPassengerPassengerPassengerPassenger,71.355,10.1,598.0,62.5
Subaru,80.135,PassengerCar,42.790,5.0,330.0,32.8
Toyota,740.205,PassengerPassengerPassengerPassengerCarCarCarC...,197.846,23.6,1446.0,159.9
Volkswagen,209.212,PassengerPassengerPassengerPassengerPassengerP...,106.190,11.8,725.0,88.2
Volvo,75.740,PassengerPassengerPassengerPassengerPassengerP...,185.600,13.8,1093.0,107.0

In [39]:
#group by vehicle_type and count values 
df_filter.groupby('Vehicle_type').count()

,Manufacturer,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,,
Car,41,41,40,40,40,40
Passenger,116,116,115,116,116,116

In [40]:
#find null values in col
df_filter.isnull().sum()

Manufacturer          0
Sales_in_thousands    0
Vehicle_type          0
Price_in_thousands    2
Engine_size           1
Horsepower            1
Fuel_capacity         1
dtype: int64

In [41]:
#group by engine_size and count values without droppping Nan values
df_filter.groupby('Engine_size',dropna=False).count()

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Horsepower,Fuel_capacity
Engine_size,,,,,,
1.0,1,1,1,1,1,1
1.5,1,1,1,1,1,1
1.6,1,1,1,1,1,1
1.8,8,8,8,8,8,8
1.9,5,5,5,5,5,5
2.0,17,17,17,17,17,17
2.2,4,4,4,4,4,4
2.3,6,6,6,6,6,6
2.4,11,11,11,11,11,11
2.5,11,11,11,11,11,11
2.7,4,4,4,4,4,4
2.8,3,3,3,3,3,3
2.9,1,1,1,1,1,1
3.0,14,14,14,14,14,14
3.1,4,4,4,4,4,4
3.2,6,6,6,5,6,6
3.3,5,5,5,5,5,5
3.4,7,7,7,7,7,7
3.5,8,8,8,8,8,8
3.8,8,8,8,8,8,8
3.9,2,2,2,2,2,2
4.0,7,7,7,7,7,7
4.2,1,1,1,1,1,1
4.3,2,2,2,2,2,2
4.6,9,9,9,9,9,9
4.7,2,2,2,2,2,2
5.0,2,2,2,2,2,2
5.2,2,2,2,2,2,2
5.4,1,1,1,1,1,1
5.7,2,2,2,2,2,2
8.0,1,1,1,1,1,1
NaN,1,1,1,0,0,0

4 Groupby() and agg()

In [44]:
#find the min and max val on each col

df_filter.groupby('Vehicle_type').min()

df_filter.groupby('Vehicle_type').max()

df_filter.groupby('Vehicle_type').agg(['min','max'])

             Manufacturer         Sales_in_thousands           \
                      min     max                min      max
Vehicle_type
Car              Cadillac  Toyota              9.126  540.561
Passenger           Acura   Volvo              0.110  247.994

             Price_in_thousands         Engine_size      Horsepower         \
                            min     max         min  max        min    max
Vehicle_type
Car                      11.528  60.105         2.0  5.7      119.0  300.0
Passenger                 9.235  85.500         1.0  8.0       55.0  450.0

             Fuel_capacity
                       min   max
Vehicle_type
Car                   15.1  32.0
Passenger             10.3  23.7

In [45]:
#set a name for aggregated col
#find the min Engine_size and max horsepower

df_filter.groupby('Vehicle_type').agg(  min_engine_size = ('Engine_size','min') , 
                                        max_horsepower  = ('Horsepower','max') )

              min_engine_size  max_horsepower
Vehicle_type
Car                       2.0           300.0
Passenger                 1.0           450.0

In [46]:
#cal the sum of Sales_in_thousands and mean of Price_in_thousands group by Manufacturer
df_filter.groupby('Manufacturer').agg(  sum_sales = ('Sales_in_thousands','sum') , 
                                        mean_price  = ('Price_in_thousands','mean') )

              sum_sales  mean_price
Manufacturer
Acura            79.005   30.633333
Audi             40.557   39.980000
BMW              46.505   33.096667
Buick           242.019   26.781250
Cadillac        112.178   40.254000
Chevrolet       554.365   20.022778
Chrysler        201.721   23.430833
Dodge           910.149   24.213636
Ford           2022.635   21.047273
Honda           592.674   20.277000
Hyundai         137.326   12.165667
Infiniti         23.713   29.465000
Jaguar           15.467   42.800000
Jeep            293.153   20.991667
Lexus           106.843   44.055000
Lincoln          85.634   41.690000
Mercedes-B      117.125   52.916667
Mercury         237.999   20.748333
Mitsubishi      180.895   22.167429
Nissan          399.635   22.360714
Oldsmobile      178.989   25.622833
Plymouth         64.001   22.642500
Pontiac         370.534   22.949167
Porsche          12.128   62.473333
Saab             21.306   29.610000
Saturn          168.850   14.271000
Subaru           80.135   21.395000
Toyota          740.205   21.982889
Volkswagen      209.212   17.698333
Volvo            75.740   30.933333

In [48]:
df_filter.groupby('Manufacturer').sum()['Sales_in_thousands']

Manufacturer
Acura           79.005
Audi            40.557
BMW             46.505
Buick          242.019
Cadillac       112.178
Chevrolet      554.365
Chrysler       201.721
Dodge          910.149
Ford          2022.635
Honda          592.674
Hyundai        137.326
Infiniti        23.713
Jaguar          15.467
Jeep           293.153
Lexus          106.843
Lincoln         85.634
Mercedes-B     117.125
Mercury        237.999
Mitsubishi     180.895
Nissan         399.635
Oldsmobile     178.989
Plymouth        64.001
Pontiac        370.534
Porsche         12.128
Saab            21.306
Saturn         168.850
Subaru          80.135
Toyota         740.205
Volkswagen     209.212
Volvo           75.740
Name: Sales_in_thousands, dtype: float64

5 Lambda

In [49]:
df_filter.groupby('Manufacturer').sum().head()

,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,,
Acura,79.005,PassengerPassengerPassengerPassenger,91.900,11.7,800.0,65.6
Audi,40.557,PassengerPassengerPassenger,119.940,8.8,660.0,58.6
BMW,46.505,PassengerPassengerPassenger,99.290,8.1,556.0,51.7
Buick,242.019,PassengerPassengerPassengerPassenger,107.125,14.5,825.0,71.0
Cadillac,112.178,PassengerPassengerPassengerPassengerCar,201.270,22.5,1280.0,104.0

In [50]:
#get actual sales and price values
#lambda x:x*1000 -> returns a number multiplied by 1000
df_filter.groupby('Manufacturer').sum().apply(lambda x:x*1000)[['Sales_in_thousands','Price_in_thousands']]

              Sales_in_thousands  Price_in_thousands
Manufacturer
Acura                    79005.0             91900.0
Audi                     40557.0            119940.0
BMW                      46505.0             99290.0
Buick                   242019.0            107125.0
Cadillac                112178.0            201270.0
Chevrolet               554365.0            180205.0
Chrysler                201721.0            140585.0
Dodge                   910149.0            266350.0
Ford                   2022635.0            231520.0
Honda                   592674.0            101385.0
Hyundai                 137326.0             36497.0
Infiniti                 23713.0             29465.0
Jaguar                   15467.0             42800.0
Jeep                    293153.0             62975.0
Lexus                   106843.0            264330.0
Lincoln                  85634.0            125070.0
Mercedes-B              117125.0            476250.0
Mercury                 237999.0            124490.0
Mitsubishi              180895.0            155172.0
Nissan                  399635.0            156525.0
Oldsmobile              178989.0            153737.0
Plymouth                 64001.0             90570.0
Pontiac                 370534.0            137695.0
Porsche                  12128.0            187420.0
Saab                     21306.0             59220.0
Saturn                  168850.0             71355.0
Subaru                   80135.0             42790.0
Toyota                  740205.0            197846.0
Volkswagen              209212.0            106190.0
Volvo                    75740.0            185600.0

In [53]:
#subtract values from the mean of each group 
#x is value in dataframe x.mean() = average values of each group like ('Bwm','audi' , group by is manufacturer)
df_filter[['Sales_in_thousands','Price_in_thousands','Manufacturer']].groupby('Manufacturer').apply(lambda x : x - x.mean())

                  Sales_in_thousands  Price_in_thousands
Manufacturer
Acura        0             -2.832250           -9.133333
             1             19.632750           -2.233333
             2             -5.637250                 NaN
             3            -11.163250           11.366667
Audi         4              6.878000          -15.990000
...                              ...                 ...
Volvo        152           -9.078333           -6.533333
             153            2.621667           -3.433333
             154            4.907667           -2.133333
             155           -9.130333           14.566667
             156            6.345667            5.066667

[157 rows x 2 columns]

6 The filter() method

In [55]:
def filter_func(x):
    #x represent a dataframe
    #52 is mean of Sales_in_thousands column
    return x['Sales_in_thousands'].sum() > 52
#we are filtering values where sum of group(ex - bmw , audi) is less than mean value of whole dataset
df_filter.groupby('Manufacturer').filter(filter_func) #porche bmw  jaguar saab audi infiniti got filtered out

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.500,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.400,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.000,3.5,210.0,18.0
10,Buick,91.561,Passenger,21.975,3.1,175.0,17.5
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.400,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.500,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.800,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.500,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.000,2.9,201.0,21.1

In [56]:
df_filter.groupby('Manufacturer').sum()['Sales_in_thousands'].sort_values()

Manufacturer
Porsche         12.128
Jaguar          15.467
Saab            21.306
Infiniti        23.713
Audi            40.557
BMW             46.505
Plymouth        64.001
Volvo           75.740
Acura           79.005
Subaru          80.135
Lincoln         85.634
Lexus          106.843
Cadillac       112.178
Mercedes-B     117.125
Hyundai        137.326
Saturn         168.850
Oldsmobile     178.989
Mitsubishi     180.895
Chrysler       201.721
Volkswagen     209.212
Mercury        237.999
Buick          242.019
Jeep           293.153
Pontiac        370.534
Nissan         399.635
Chevrolet      554.365
Honda          592.674
Toyota         740.205
Dodge          910.149
Ford          2022.635
Name: Sales_in_thousands, dtype: float64