In [2]:
def function1():
    return 2+5
function1()

7

In [3]:
def sumvalues(a,b):
    return a+b
sumvalues(2,15)

17

In [4]:
sumvalues(7,9)

16

built in function

In [5]:
countries = ['usa','india','china','japan','south korea']

In [6]:
type(countries)

list

In [8]:
if type(countries) == list:
    print(f"type of list")

type of list

In [11]:
for i in range(0,10,2):
    print(f"even number is {i}",end=" ,")

even number is 0 ,even number is 2 ,even number is 4 ,even number is 6 ,even number is 8 ,

Modules

use import to import a module ,

OS module

In [12]:
import os

In [13]:
os.getcwd()

'C:\\Users\\shewa'

In [16]:
os.listdir()

['.anaconda',
 '.android',
 '.bash_history',
 '.cisco',
 '.conda',
 '.config',
 '.continuum',
 '.docker',
 '.eclipse',
 '.git',
 '.gitconfig',
 '.gradle',
 '.h2.server.properties',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jdks',
 '.jenkins',
 '.jupyter',
 '.lesshst',
 '.m2',
 '.ollama',
 '.p2',
 '.th-client',
 '.tooling',
 '.viminfo',
 '.VirtualBox',
 '.vscode',
 '3D Objects',
 'anaconda3',
 'anaconda_projects',
 'AndroidStudioProjects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'eclipse',
 'eclipse-workspace',
 'Envs',
 'Favorites',
 'foldercreatedbypythoncode',
 'Links',
 'Local Settings',
 'mercurial.ini',
 'MicrosoftEdgeBackups',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{b9ed6fdc-dede-11ef-9cc3-a08b49dfcbf9}.TM.blf',
 'NTUSER.DAT{b9ed6fdc-dede-11ef-9cc3-a08b49dfcbf9}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{b9ed6fdc-dede-11ef-9cc3-a08b49dfcbf9}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Postman',
 'PrintHood',
 'README.md',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Videos']

In [15]:
os.makedirs('foldercreatedbypythoncode')

Creating a dataframe in python

In [17]:
import pandas as pd

In [18]:
import numpy as np

In [19]:
#creating an array
data = np.array([[1,4], [2,5] , [3,6] , [7,8] ])

In [21]:
#creating a dataframe
df  = pd.DataFrame(data, index = ['row1','row2','row3','row4'] , columns=['col1','col2'] )

In [22]:
#showing the dataframe

In [23]:
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6
row4     7     8

In [24]:
pythonlist = [[1,4], [2,5] , [3,6] , [7,8] ]

In [25]:
dfpython  = pd.DataFrame(pythonlist, index = ['row1','row2','row3','row4'] , columns=['col1','col2'] )
dfpython

      col1  col2
row1     1     4
row2     2     5
row3     3     6
row4     7     8

creating dataframe from dictionary

In [26]:
states = ['california' , 'texas', 'florida','new work']
population = [1334523,98345,16579,234870]

In [27]:
dict_states = {'states':states,'population' : population}
df_population = pd.DataFrame(dict_states)
#showing data frame
df_population

       states  population
0  california     1334523
1       texas       98345
2     florida       16579
3    new work      234870

Create a dataframe from a csv file

In [30]:
#reading from csv file 
df_exams = pd.read_csv('StudentsPerformance.csv')
#file should be in same folder use os.getcwd() to get current working directory 

#show first 5 rows of dataframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [32]:
#show last 5 rows in a dataframe
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [33]:
#show last n rows in a dataframe

df_exams.tail(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [34]:
#show first n rows in a dataframe

df_exams.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [35]:
#getting access to shape attribute
rows,cols = df_exams.shape
pd.set_option('display.max_rows',rows)

df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48
51,male,group E,associate's degree,free/reduced,completed,77,69,68
52,male,group C,some college,standard,none,53,44,42
53,male,group D,high school,standard,none,88,78,75
54,female,group C,some high school,free/reduced,completed,71,84,87
55,female,group C,high school,free/reduced,none,33,41,43
56,female,group E,associate's degree,standard,completed,82,85,86
57,male,group D,associate's degree,standard,none,52,55,49
58,male,group D,some college,standard,completed,58,59,58
59,female,group C,some high school,free/reduced,none,0,17,10
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72
61,male,group A,some high school,free/reduced,none,39,39,34
62,male,group A,associate's degree,free/reduced,none,62,61,55
63,female,group C,associate's degree,standard,none,69,80,71
64,female,group D,some high school,standard,none,59,58,59
65,male,group B,some high school,standard,none,67,64,61
66,male,group D,some high school,free/reduced,none,45,37,37
67,female,group C,some college,standard,none,60,72,74
68,male,group B,associate's degree,free/reduced,none,61,58,56
69,female,group C,associate's degree,standard,none,39,64,57
70,female,group D,some college,free/reduced,completed,58,63,73
71,male,group D,some college,standard,completed,63,55,63
72,female,group A,associate's degree,free/reduced,none,41,51,48
73,male,group C,some high school,free/reduced,none,61,57,56
74,male,group C,some high school,standard,none,49,49,41
75,male,group B,associate's degree,free/reduced,none,44,41,38
76,male,group E,some high school,standard,none,30,26,22
77,male,group A,bachelor's degree,standard,completed,80,78,81
78,female,group D,some high school,standard,completed,61,74,72
79,female,group E,master's degree,standard,none,62,68,68
80,female,group B,associate's degree,standard,none,47,49,50
81,male,group B,high school,free/reduced,none,49,45,45
82,male,group A,some college,free/reduced,completed,50,47,54
83,male,group E,associate's degree,standard,none,72,64,63
84,male,group D,high school,free/reduced,none,42,39,34
85,female,group C,some college,standard,none,73,80,82
86,female,group C,some college,free/reduced,none,76,83,88
87,female,group D,associate's degree,standard,none,71,71,74
88,female,group A,some college,standard,none,58,70,67
89,female,group D,some high school,standard,none,73,86,82
90,female,group C,bachelor's degree,standard,none,65,72,74
91,male,group C,high school,free/reduced,none,27,34,36
92,male,group C,high school,standard,none,71,79,71
93,male,group C,associate's degree,free/reduced,completed,43,45,50
94,female,group B,some college,standard,none,79,86,92
95,male,group C,associate's degree,free/reduced,completed,78,81,82
96,male,group B,some high school,standard,completed,65,66,62
97,female,group E,some college,standard,completed,63,72,70
98,female,group D,some college,free/reduced,none,58,67,62
99,female,group D,bachelor's degree,standard,none,65,67,62
100,male,group B,some college,standard,none,79,67,67
101,male,group D,bachelor's degree,standard,completed,68,74,74
102,female,group D,associate's degree,standard,none,85,91,89
103,male,group B,high school,standard,completed,60,44,47
104,male,group C,some college,standard,completed,98,86,90
105,female,group C,some college,standard,none,58,67,72
106,female,group D,master's degree,standard,none,87,100,100
107,male,group E,associate's degree,standard,completed,66,63,64
108,female,group B,associate's degree,free/reduced,none,52,76,70
109,female,group B,some high school,standard,none,70,64,72
110,female,group D,associate's degree,free/reduced,completed,77,89,98
111,male,group C,high school,standard,none,62,55,49
112,male,group A,associate's degree,standard,none,54,53,47
113,female,group D,some college,standard,none,51,58,54
114,female,group E,bachelor's degree,standard,completed,99,100,100
115,male,group C,high school,standard,none,84,77,74
116,female,group B,bachelor's degree,free/reduced,none,75,85,82
117,female,group D,bachelor's degree,standard,none,78,82,79
118,female,group D,some high school,standard,none,51,63,61
119,female,group C,some college,standard,none,55,69,65
120,female,group C,bachelor's degree,standard,completed,79,92,89
121,male,group B,associate's degree,standard,completed,91,89,92
122,female,group C,some college,standard,completed,88,93,93
123,male,group D,high school,free/reduced,none,63,57,56
124,male,group E,some college,standard,none,83,80,73
125,female,group B,high school,standard,none,87,95,86
126,male,group B,some high school,standard,none,72,68,67
127,male,group D,some college,standard,completed,65,77,74
128,male,group D,master's degree,standard,none,82,82,74
129,female,group A,bachelor's degree,standard,none,51,49,51
130,male,group D,master's degree,standard,none,89,84,82
131,male,group C,some high school,free/reduced,completed,53,37,40
132,male,group E,some college,free/reduced,completed,87,74,70
133,female,group C,some college,standard,completed,75,81,84
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75
135,male,group C,bachelor's degree,standard,none,58,55,48
136,male,group B,some high school,standard,completed,51,54,41
137,male,group E,high school,standard,none,70,55,56
138,female,group C,associate's degree,standard,none,59,66,67
139,male,group D,some college,standard,completed,71,61,69
140,female,group D,some high school,standard,none,76,72,71
141,female,group C,some college,free/reduced,none,59,62,64
142,female,group E,some college,free/reduced,completed,42,55,54
143,male,group A,high school,standard,none,57,43,47
144,male,group D,some college,standard,none,88,73,78
145,female,group C,some college,free/reduced,none,22,39,33
146,male,group B,some high school,standard,none,88,84,75
147,male,group C,associate's degree,free/reduced,none,73,68,66
148,female,group D,bachelor's degree,standard,completed,68,75,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
150,male,group A,some high school,standard,completed,62,67,69
151,male,group A,bachelor's degree,standard,none,77,67,68
152,female,group B,associate's degree,standard,completed,59,70,66
153,male,group D,bachelor's degree,standard,none,54,49,47
154,male,group D,some high school,standard,none,62,67,61
155,female,group C,some college,standard,completed,70,89,88
156,female,group E,high school,free/reduced,completed,66,74,78
157,male,group B,some college,free/reduced,none,60,60,60
158,female,group B,associate's degree,standard,completed,61,86,87
159,male,group D,associate's degree,free/reduced,none,66,62,64
160,male,group B,associate's degree,free/reduced,completed,82,78,74
161,female,group E,some college,free/reduced,completed,75,88,85
162,male,group B,master's degree,free/reduced,none,49,53,52
163,male,group C,high school,standard,none,52,53,49
164,female,group E,master's degree,standard,none,81,92,91
165,female,group C,bachelor's degree,standard,completed,96,100,100
166,male,group C,high school,free/reduced,completed,53,51,51
167,female,group B,master's degree,free/reduced,completed,58,76,78
168,female,group B,high school,standard,completed,68,83,78
169,female,group C,some college,free/reduced,completed,67,75,70
170,male,group A,high school,standard,completed,72,73,74
171,male,group E,some high school,standard,none,94,88,78
172,female,group D,some college,standard,none,79,86,81
173,female,group C,associate's degree,standard,none,63,67,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54
175,female,group C,master's degree,standard,completed,81,91,87
176,female,group B,high school,free/reduced,completed,46,54,58
177,female,group C,associate's degree,standard,completed,71,77,77
178,female,group B,master's degree,free/reduced,completed,52,70,62
179,female,group D,some high school,standard,completed,97,100,100
180,male,group C,master's degree,free/reduced,completed,62,68,75
181,female,group C,some college,free/reduced,none,46,64,66
182,female,group E,high school,standard,none,50,50,47
183,female,group D,associate's degree,standard,none,65,69,70
184,male,group C,some high school,free/reduced,completed,45,52,49
185,male,group C,associate's degree,free/reduced,completed,65,67,65
186,male,group E,high school,standard,none,80,76,65
187,male,group D,some high school,standard,completed,62,66,68
188,male,group B,some high school,free/reduced,none,48,52,45
189,female,group C,bachelor's degree,standard,none,77,88,87
190,female,group E,associate's degree,standard,none,66,65,69
191,male,group D,some college,standard,completed,76,83,79
192,female,group B,some high school,standard,none,62,64,66
193,male,group D,some college,standard,completed,77,62,62
194,female,group C,master's degree,standard,completed,69,84,85
195,male,group D,associate's degree,standard,none,61,55,52
196,male,group C,some high school,free/reduced,completed,59,69,65
197,male,group E,high school,free/reduced,none,55,56,51
198,female,group B,some college,free/reduced,none,45,53,55
199,female,group B,bachelor's degree,free/reduced,none,78,79,76
200,female,group C,associate's degree,standard,completed,67,84,86
201,female,group D,some college,free/reduced,none,65,81,77
202,male,group C,associate's degree,standard,none,69,77,69
203,female,group B,associate's degree,standard,none,57,69,68
204,male,group C,some college,standard,none,59,41,42
205,male,group D,some high school,standard,completed,74,71,78
206,male,group E,bachelor's degree,standard,none,82,62,62
207,male,group E,high school,standard,completed,81,80,76
208,female,group B,some college,free/reduced,none,74,81,76
209,female,group B,some college,free/reduced,none,58,61,66
210,male,group D,some high school,free/reduced,completed,80,79,79
211,male,group C,some college,free/reduced,none,35,28,27
212,female,group C,high school,free/reduced,none,42,62,60
213,male,group C,associate's degree,free/reduced,completed,60,51,56
214,male,group E,high school,standard,completed,87,91,81
215,male,group B,some high school,standard,completed,84,83,75
216,female,group E,associate's degree,free/reduced,completed,83,86,88
217,female,group C,high school,free/reduced,none,34,42,39
218,male,group B,high school,free/reduced,none,66,77,70
219,male,group B,some high school,standard,completed,61,56,56
220,female,group D,high school,standard,completed,56,68,74
221,male,group B,associate's degree,standard,none,87,85,73
222,female,group C,some high school,free/reduced,none,55,65,62
223,male,group D,some high school,standard,none,86,80,75
224,female,group B,associate's degree,standard,completed,52,66,73
225,female,group E,master's degree,free/reduced,none,45,56,54
226,female,group C,some college,standard,none,72,72,71
227,male,group D,high school,standard,none,57,50,54
228,male,group A,some high school,free/reduced,none,68,72,64
229,female,group C,some college,standard,completed,88,95,94
230,male,group D,some college,standard,none,76,64,66
231,male,group C,associate's degree,standard,none,46,43,42
232,female,group B,bachelor's degree,standard,none,67,86,83
233,male,group E,some high school,standard,none,92,87,78
234,male,group C,bachelor's degree,standard,completed,83,82,84
235,male,group D,associate's degree,standard,none,80,75,77
236,male,group D,bachelor's degree,free/reduced,none,63,66,67
237,female,group D,some high school,standard,completed,64,60,74
238,male,group B,some college,standard,none,54,52,51
239,male,group C,associate's degree,standard,none,84,80,80
240,male,group D,high school,free/reduced,completed,73,68,66
241,female,group E,bachelor's degree,standard,none,80,83,83
242,female,group D,high school,standard,none,56,52,55
243,male,group E,some college,standard,none,59,51,43
244,male,group D,some high school,standard,none,75,74,69
245,male,group C,associate's degree,standard,none,85,76,71
246,male,group E,associate's degree,standard,none,89,76,74
247,female,group B,high school,standard,completed,58,70,68
248,female,group B,high school,standard,none,65,64,62
249,male,group C,high school,standard,none,68,60,53
250,male,group A,some high school,standard,completed,47,49,49
251,female,group D,some college,free/reduced,none,71,83,83
252,female,group B,some high school,standard,completed,60,70,70
253,male,group D,master's degree,standard,none,80,80,72
254,male,group D,high school,standard,none,54,52,52
255,female,group E,some college,standard,none,62,73,70
256,female,group C,associate's degree,free/reduced,none,64,73,68
257,male,group C,associate's degree,standard,completed,78,77,77
258,female,group B,some college,standard,none,70,75,78
259,female,group C,master's degree,free/reduced,completed,65,81,81
260,female,group C,some high school,free/reduced,completed,64,79,77
261,male,group C,some college,standard,completed,79,79,78
262,female,group C,some high school,free/reduced,none,44,50,51
263,female,group E,high school,standard,none,99,93,90
264,male,group D,high school,standard,none,76,73,68
265,male,group D,some high school,free/reduced,none,59,42,41
266,female,group C,bachelor's degree,standard,none,63,75,81
267,female,group D,high school,standard,none,69,72,77
268,female,group D,associate's degree,standard,completed,88,92,95
269,female,group E,some college,free/reduced,none,71,76,70
270,male,group C,bachelor's degree,standard,none,69,63,61
271,male,group C,some college,standard,none,58,49,42
272,female,group D,associate's degree,free/reduced,none,47,53,58
273,female,group D,some college,standard,none,65,70,71
274,male,group B,some college,standard,completed,88,85,76
275,male,group C,bachelor's degree,standard,none,83,78,73
276,female,group C,some high school,standard,completed,85,92,93
277,female,group E,high school,standard,completed,59,63,75
278,female,group C,some high school,free/reduced,none,65,86,80
279,male,group B,bachelor's degree,free/reduced,none,73,56,57
280,male,group D,high school,standard,none,53,52,42
281,male,group D,high school,standard,none,45,48,46
282,female,group D,bachelor's degree,free/reduced,none,73,79,84
283,female,group D,some college,free/reduced,completed,70,78,78
284,female,group B,some high school,standard,none,37,46,46
285,male,group B,associate's degree,standard,completed,81,82,82
286,male,group E,associate's degree,standard,completed,97,82,88
287,female,group B,some high school,standard,none,67,89,82
288,male,group B,bachelor's degree,free/reduced,none,88,75,76
289,male,group E,some high school,standard,completed,77,76,77
290,male,group C,associate's degree,standard,none,76,70,68
291,male,group D,some high school,standard,none,86,73,70
292,male,group C,some high school,standard,completed,63,60,57
293,female,group E,bachelor's degree,standard,none,65,73,75
294,male,group D,high school,free/reduced,completed,78,77,80
295,male,group B,associate's degree,free/reduced,none,67,62,60
296,male,group A,some high school,standard,completed,46,41,43
297,male,group E,associate's degree,standard,completed,71,74,68
298,male,group C,high school,free/reduced,completed,40,46,50
299,male,group D,associate's degree,free/reduced,none,90,87,75
300,male,group A,some college,free/reduced,completed,81,78,81
301,male,group D,some high school,free/reduced,none,56,54,52
302,female,group C,associate's degree,standard,completed,67,84,81
303,male,group B,associate's degree,standard,none,80,76,64
304,female,group C,associate's degree,standard,completed,74,75,83
305,male,group A,some college,standard,none,69,67,69
306,male,group E,some college,standard,completed,99,87,81
307,male,group C,some high school,standard,none,51,52,44
308,female,group B,associate's degree,free/reduced,none,53,71,67
309,female,group D,high school,free/reduced,none,49,57,52
310,female,group B,associate's degree,standard,none,73,76,80
311,male,group B,bachelor's degree,standard,none,66,60,57
312,male,group D,bachelor's degree,standard,completed,67,61,68
313,female,group C,associate's degree,free/reduced,completed,68,67,69
314,female,group C,bachelor's degree,standard,completed,59,64,75
315,male,group C,high school,standard,none,71,66,65
316,female,group D,master's degree,standard,completed,77,82,91
317,male,group C,associate's degree,standard,none,83,72,78
318,male,group B,bachelor's degree,standard,none,63,71,69
319,female,group D,associate's degree,free/reduced,none,56,65,63
320,female,group C,high school,free/reduced,completed,67,79,84
321,female,group E,high school,standard,none,75,86,79
322,female,group C,some college,standard,none,71,81,80
323,female,group C,some high school,free/reduced,none,43,53,53
324,female,group C,high school,free/reduced,none,41,46,43
325,female,group C,some college,standard,none,82,90,94
326,male,group C,some college,standard,none,61,61,62
327,male,group A,some college,free/reduced,none,28,23,19
328,male,group C,associate's degree,standard,completed,82,75,77
329,female,group B,some high school,standard,none,41,55,51
330,male,group C,high school,standard,none,71,60,61
331,male,group C,associate's degree,standard,none,47,37,35
332,male,group E,associate's degree,standard,completed,62,56,53

Basic attributes , methods and functions

In [36]:
df_exams.shape

(1000, 8)

In [37]:
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [38]:
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [39]:
#data type of each column 
df_exams.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [40]:
df_exams.head()
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [41]:
#describing basic statistics of the dataframe
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [42]:
len(df_exams)

1000

In [43]:

#obtain the data type
type(df_exams)

pandas.core.frame.DataFrame

In [44]:
#round the values of dataframe
round(df_exams, 2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48
51,male,group E,associate's degree,free/reduced,completed,77,69,68
52,male,group C,some college,standard,none,53,44,42
53,male,group D,high school,standard,none,88,78,75
54,female,group C,some high school,free/reduced,completed,71,84,87
55,female,group C,high school,free/reduced,none,33,41,43
56,female,group E,associate's degree,standard,completed,82,85,86
57,male,group D,associate's degree,standard,none,52,55,49
58,male,group D,some college,standard,completed,58,59,58
59,female,group C,some high school,free/reduced,none,0,17,10
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72
61,male,group A,some high school,free/reduced,none,39,39,34
62,male,group A,associate's degree,free/reduced,none,62,61,55
63,female,group C,associate's degree,standard,none,69,80,71
64,female,group D,some high school,standard,none,59,58,59
65,male,group B,some high school,standard,none,67,64,61
66,male,group D,some high school,free/reduced,none,45,37,37
67,female,group C,some college,standard,none,60,72,74
68,male,group B,associate's degree,free/reduced,none,61,58,56
69,female,group C,associate's degree,standard,none,39,64,57
70,female,group D,some college,free/reduced,completed,58,63,73
71,male,group D,some college,standard,completed,63,55,63
72,female,group A,associate's degree,free/reduced,none,41,51,48
73,male,group C,some high school,free/reduced,none,61,57,56
74,male,group C,some high school,standard,none,49,49,41
75,male,group B,associate's degree,free/reduced,none,44,41,38
76,male,group E,some high school,standard,none,30,26,22
77,male,group A,bachelor's degree,standard,completed,80,78,81
78,female,group D,some high school,standard,completed,61,74,72
79,female,group E,master's degree,standard,none,62,68,68
80,female,group B,associate's degree,standard,none,47,49,50
81,male,group B,high school,free/reduced,none,49,45,45
82,male,group A,some college,free/reduced,completed,50,47,54
83,male,group E,associate's degree,standard,none,72,64,63
84,male,group D,high school,free/reduced,none,42,39,34
85,female,group C,some college,standard,none,73,80,82
86,female,group C,some college,free/reduced,none,76,83,88
87,female,group D,associate's degree,standard,none,71,71,74
88,female,group A,some college,standard,none,58,70,67
89,female,group D,some high school,standard,none,73,86,82
90,female,group C,bachelor's degree,standard,none,65,72,74
91,male,group C,high school,free/reduced,none,27,34,36
92,male,group C,high school,standard,none,71,79,71
93,male,group C,associate's degree,free/reduced,completed,43,45,50
94,female,group B,some college,standard,none,79,86,92
95,male,group C,associate's degree,free/reduced,completed,78,81,82
96,male,group B,some high school,standard,completed,65,66,62
97,female,group E,some college,standard,completed,63,72,70
98,female,group D,some college,free/reduced,none,58,67,62
99,female,group D,bachelor's degree,standard,none,65,67,62
100,male,group B,some college,standard,none,79,67,67
101,male,group D,bachelor's degree,standard,completed,68,74,74
102,female,group D,associate's degree,standard,none,85,91,89
103,male,group B,high school,standard,completed,60,44,47
104,male,group C,some college,standard,completed,98,86,90
105,female,group C,some college,standard,none,58,67,72
106,female,group D,master's degree,standard,none,87,100,100
107,male,group E,associate's degree,standard,completed,66,63,64
108,female,group B,associate's degree,free/reduced,none,52,76,70
109,female,group B,some high school,standard,none,70,64,72
110,female,group D,associate's degree,free/reduced,completed,77,89,98
111,male,group C,high school,standard,none,62,55,49
112,male,group A,associate's degree,standard,none,54,53,47
113,female,group D,some college,standard,none,51,58,54
114,female,group E,bachelor's degree,standard,completed,99,100,100
115,male,group C,high school,standard,none,84,77,74
116,female,group B,bachelor's degree,free/reduced,none,75,85,82
117,female,group D,bachelor's degree,standard,none,78,82,79
118,female,group D,some high school,standard,none,51,63,61
119,female,group C,some college,standard,none,55,69,65
120,female,group C,bachelor's degree,standard,completed,79,92,89
121,male,group B,associate's degree,standard,completed,91,89,92
122,female,group C,some college,standard,completed,88,93,93
123,male,group D,high school,free/reduced,none,63,57,56
124,male,group E,some college,standard,none,83,80,73
125,female,group B,high school,standard,none,87,95,86
126,male,group B,some high school,standard,none,72,68,67
127,male,group D,some college,standard,completed,65,77,74
128,male,group D,master's degree,standard,none,82,82,74
129,female,group A,bachelor's degree,standard,none,51,49,51
130,male,group D,master's degree,standard,none,89,84,82
131,male,group C,some high school,free/reduced,completed,53,37,40
132,male,group E,some college,free/reduced,completed,87,74,70
133,female,group C,some college,standard,completed,75,81,84
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75
135,male,group C,bachelor's degree,standard,none,58,55,48
136,male,group B,some high school,standard,completed,51,54,41
137,male,group E,high school,standard,none,70,55,56
138,female,group C,associate's degree,standard,none,59,66,67
139,male,group D,some college,standard,completed,71,61,69
140,female,group D,some high school,standard,none,76,72,71
141,female,group C,some college,free/reduced,none,59,62,64
142,female,group E,some college,free/reduced,completed,42,55,54
143,male,group A,high school,standard,none,57,43,47
144,male,group D,some college,standard,none,88,73,78
145,female,group C,some college,free/reduced,none,22,39,33
146,male,group B,some high school,standard,none,88,84,75
147,male,group C,associate's degree,free/reduced,none,73,68,66
148,female,group D,bachelor's degree,standard,completed,68,75,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
150,male,group A,some high school,standard,completed,62,67,69
151,male,group A,bachelor's degree,standard,none,77,67,68
152,female,group B,associate's degree,standard,completed,59,70,66
153,male,group D,bachelor's degree,standard,none,54,49,47
154,male,group D,some high school,standard,none,62,67,61
155,female,group C,some college,standard,completed,70,89,88
156,female,group E,high school,free/reduced,completed,66,74,78
157,male,group B,some college,free/reduced,none,60,60,60
158,female,group B,associate's degree,standard,completed,61,86,87
159,male,group D,associate's degree,free/reduced,none,66,62,64
160,male,group B,associate's degree,free/reduced,completed,82,78,74
161,female,group E,some college,free/reduced,completed,75,88,85
162,male,group B,master's degree,free/reduced,none,49,53,52
163,male,group C,high school,standard,none,52,53,49
164,female,group E,master's degree,standard,none,81,92,91
165,female,group C,bachelor's degree,standard,completed,96,100,100
166,male,group C,high school,free/reduced,completed,53,51,51
167,female,group B,master's degree,free/reduced,completed,58,76,78
168,female,group B,high school,standard,completed,68,83,78
169,female,group C,some college,free/reduced,completed,67,75,70
170,male,group A,high school,standard,completed,72,73,74
171,male,group E,some high school,standard,none,94,88,78
172,female,group D,some college,standard,none,79,86,81
173,female,group C,associate's degree,standard,none,63,67,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54
175,female,group C,master's degree,standard,completed,81,91,87
176,female,group B,high school,free/reduced,completed,46,54,58
177,female,group C,associate's degree,standard,completed,71,77,77
178,female,group B,master's degree,free/reduced,completed,52,70,62
179,female,group D,some high school,standard,completed,97,100,100
180,male,group C,master's degree,free/reduced,completed,62,68,75
181,female,group C,some college,free/reduced,none,46,64,66
182,female,group E,high school,standard,none,50,50,47
183,female,group D,associate's degree,standard,none,65,69,70
184,male,group C,some high school,free/reduced,completed,45,52,49
185,male,group C,associate's degree,free/reduced,completed,65,67,65
186,male,group E,high school,standard,none,80,76,65
187,male,group D,some high school,standard,completed,62,66,68
188,male,group B,some high school,free/reduced,none,48,52,45
189,female,group C,bachelor's degree,standard,none,77,88,87
190,female,group E,associate's degree,standard,none,66,65,69
191,male,group D,some college,standard,completed,76,83,79
192,female,group B,some high school,standard,none,62,64,66
193,male,group D,some college,standard,completed,77,62,62
194,female,group C,master's degree,standard,completed,69,84,85
195,male,group D,associate's degree,standard,none,61,55,52
196,male,group C,some high school,free/reduced,completed,59,69,65
197,male,group E,high school,free/reduced,none,55,56,51
198,female,group B,some college,free/reduced,none,45,53,55
199,female,group B,bachelor's degree,free/reduced,none,78,79,76
200,female,group C,associate's degree,standard,completed,67,84,86
201,female,group D,some college,free/reduced,none,65,81,77
202,male,group C,associate's degree,standard,none,69,77,69
203,female,group B,associate's degree,standard,none,57,69,68
204,male,group C,some college,standard,none,59,41,42
205,male,group D,some high school,standard,completed,74,71,78
206,male,group E,bachelor's degree,standard,none,82,62,62
207,male,group E,high school,standard,completed,81,80,76
208,female,group B,some college,free/reduced,none,74,81,76
209,female,group B,some college,free/reduced,none,58,61,66
210,male,group D,some high school,free/reduced,completed,80,79,79
211,male,group C,some college,free/reduced,none,35,28,27
212,female,group C,high school,free/reduced,none,42,62,60
213,male,group C,associate's degree,free/reduced,completed,60,51,56
214,male,group E,high school,standard,completed,87,91,81
215,male,group B,some high school,standard,completed,84,83,75
216,female,group E,associate's degree,free/reduced,completed,83,86,88
217,female,group C,high school,free/reduced,none,34,42,39
218,male,group B,high school,free/reduced,none,66,77,70
219,male,group B,some high school,standard,completed,61,56,56
220,female,group D,high school,standard,completed,56,68,74
221,male,group B,associate's degree,standard,none,87,85,73
222,female,group C,some high school,free/reduced,none,55,65,62
223,male,group D,some high school,standard,none,86,80,75
224,female,group B,associate's degree,standard,completed,52,66,73
225,female,group E,master's degree,free/reduced,none,45,56,54
226,female,group C,some college,standard,none,72,72,71
227,male,group D,high school,standard,none,57,50,54
228,male,group A,some high school,free/reduced,none,68,72,64
229,female,group C,some college,standard,completed,88,95,94
230,male,group D,some college,standard,none,76,64,66
231,male,group C,associate's degree,standard,none,46,43,42
232,female,group B,bachelor's degree,standard,none,67,86,83
233,male,group E,some high school,standard,none,92,87,78
234,male,group C,bachelor's degree,standard,completed,83,82,84
235,male,group D,associate's degree,standard,none,80,75,77
236,male,group D,bachelor's degree,free/reduced,none,63,66,67
237,female,group D,some high school,standard,completed,64,60,74
238,male,group B,some college,standard,none,54,52,51
239,male,group C,associate's degree,standard,none,84,80,80
240,male,group D,high school,free/reduced,completed,73,68,66
241,female,group E,bachelor's degree,standard,none,80,83,83
242,female,group D,high school,standard,none,56,52,55
243,male,group E,some college,standard,none,59,51,43
244,male,group D,some high school,standard,none,75,74,69
245,male,group C,associate's degree,standard,none,85,76,71
246,male,group E,associate's degree,standard,none,89,76,74
247,female,group B,high school,standard,completed,58,70,68
248,female,group B,high school,standard,none,65,64,62
249,male,group C,high school,standard,none,68,60,53
250,male,group A,some high school,standard,completed,47,49,49
251,female,group D,some college,free/reduced,none,71,83,83
252,female,group B,some high school,standard,completed,60,70,70
253,male,group D,master's degree,standard,none,80,80,72
254,male,group D,high school,standard,none,54,52,52
255,female,group E,some college,standard,none,62,73,70
256,female,group C,associate's degree,free/reduced,none,64,73,68
257,male,group C,associate's degree,standard,completed,78,77,77
258,female,group B,some college,standard,none,70,75,78
259,female,group C,master's degree,free/reduced,completed,65,81,81
260,female,group C,some high school,free/reduced,completed,64,79,77
261,male,group C,some college,standard,completed,79,79,78
262,female,group C,some high school,free/reduced,none,44,50,51
263,female,group E,high school,standard,none,99,93,90
264,male,group D,high school,standard,none,76,73,68
265,male,group D,some high school,free/reduced,none,59,42,41
266,female,group C,bachelor's degree,standard,none,63,75,81
267,female,group D,high school,standard,none,69,72,77
268,female,group D,associate's degree,standard,completed,88,92,95
269,female,group E,some college,free/reduced,none,71,76,70
270,male,group C,bachelor's degree,standard,none,69,63,61
271,male,group C,some college,standard,none,58,49,42
272,female,group D,associate's degree,free/reduced,none,47,53,58
273,female,group D,some college,standard,none,65,70,71
274,male,group B,some college,standard,completed,88,85,76
275,male,group C,bachelor's degree,standard,none,83,78,73
276,female,group C,some high school,standard,completed,85,92,93
277,female,group E,high school,standard,completed,59,63,75
278,female,group C,some high school,free/reduced,none,65,86,80
279,male,group B,bachelor's degree,free/reduced,none,73,56,57
280,male,group D,high school,standard,none,53,52,42
281,male,group D,high school,standard,none,45,48,46
282,female,group D,bachelor's degree,free/reduced,none,73,79,84
283,female,group D,some college,free/reduced,completed,70,78,78
284,female,group B,some high school,standard,none,37,46,46
285,male,group B,associate's degree,standard,completed,81,82,82
286,male,group E,associate's degree,standard,completed,97,82,88
287,female,group B,some high school,standard,none,67,89,82
288,male,group B,bachelor's degree,free/reduced,none,88,75,76
289,male,group E,some high school,standard,completed,77,76,77
290,male,group C,associate's degree,standard,none,76,70,68
291,male,group D,some high school,standard,none,86,73,70
292,male,group C,some high school,standard,completed,63,60,57
293,female,group E,bachelor's degree,standard,none,65,73,75
294,male,group D,high school,free/reduced,completed,78,77,80
295,male,group B,associate's degree,free/reduced,none,67,62,60
296,male,group A,some high school,standard,completed,46,41,43
297,male,group E,associate's degree,standard,completed,71,74,68
298,male,group C,high school,free/reduced,completed,40,46,50
299,male,group D,associate's degree,free/reduced,none,90,87,75
300,male,group A,some college,free/reduced,completed,81,78,81
301,male,group D,some high school,free/reduced,none,56,54,52
302,female,group C,associate's degree,standard,completed,67,84,81
303,male,group B,associate's degree,standard,none,80,76,64
304,female,group C,associate's degree,standard,completed,74,75,83
305,male,group A,some college,standard,none,69,67,69
306,male,group E,some college,standard,completed,99,87,81
307,male,group C,some high school,standard,none,51,52,44
308,female,group B,associate's degree,free/reduced,none,53,71,67
309,female,group D,high school,free/reduced,none,49,57,52
310,female,group B,associate's degree,standard,none,73,76,80
311,male,group B,bachelor's degree,standard,none,66,60,57
312,male,group D,bachelor's degree,standard,completed,67,61,68
313,female,group C,associate's degree,free/reduced,completed,68,67,69
314,female,group C,bachelor's degree,standard,completed,59,64,75
315,male,group C,high school,standard,none,71,66,65
316,female,group D,master's degree,standard,completed,77,82,91
317,male,group C,associate's degree,standard,none,83,72,78
318,male,group B,bachelor's degree,standard,none,63,71,69
319,female,group D,associate's degree,free/reduced,none,56,65,63
320,female,group C,high school,free/reduced,completed,67,79,84
321,female,group E,high school,standard,none,75,86,79
322,female,group C,some college,standard,none,71,81,80
323,female,group C,some high school,free/reduced,none,43,53,53
324,female,group C,high school,free/reduced,none,41,46,43
325,female,group C,some college,standard,none,82,90,94
326,male,group C,some college,standard,none,61,61,62
327,male,group A,some college,free/reduced,none,28,23,19
328,male,group C,associate's degree,standard,completed,82,75,77
329,female,group B,some high school,standard,none,41,55,51
330,male,group C,high school,standard,none,71,60,61
331,male,group C,associate's degree,standard,none,47,37,35
332,male,group E,associate's degree,standard,completed,62,56,53

Selecting 1 column from a data frame

In [47]:
df_exams['gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [46]:
pd.set_option('display.max_rows',10)

In [48]:
#check data type of a column
type(df_exams['gender'])

pandas.core.series.Series

In [49]:
df_exams['gender'].index

RangeIndex(start=0, stop=1000, step=1)

In [50]:
df_exams['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

In [51]:
df_exams.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [53]:
#if space is in column name we can't use . to get column 
df_exams['math score']

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

Selecting 2 or more columns from a dataframe

In [55]:
#we can define the order of column name in the square brackets []
df_exams[['gender','math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [56]:
type(df_exams[['gender','math score']]) #dataframe

pandas.core.frame.DataFrame

In [57]:
#when we use 2 pair of [[]] brackets we get a dataframe
#when we use 1 pair of [] we get a series
df_exams[['gender','math score','lunch']]

     gender  math score         lunch
0    female          72      standard
1    female          69      standard
2    female          90      standard
3      male          47  free/reduced
4      male          76      standard
..      ...         ...           ...
995  female          88      standard
996    male          62  free/reduced
997  female          59  free/reduced
998  female          68      standard
999  female          77  free/reduced

[1000 rows x 3 columns]

In [58]:
#we can only select 1 column with . operator
df_exams.gender #does not work for multiple columns

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

Add new column to a dataframe

In [59]:
#adding a new column to dataframe
#adding new column with a scaler value all rows will have a single value
df_exams['language score'] = 70

In [60]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

In [61]:
#adding a new column with numpy arrays
#create an array of 1000 elements 

language_score = np.arange(0,1000)

In [62]:
#adding new column to dataframe 
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [63]:
# create random integer number between  1 and 100 , 100 is exclusive, so  max is 99
language_score =  np.random.randint(1,100 , size = 1000)

In [64]:
df_exams['language_score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score
0,female,group B,bachelor's degree,standard,none,72,72,74,0,83
1,female,group C,some college,standard,completed,69,90,88,1,90
2,female,group B,master's degree,standard,none,90,95,93,2,44
3,male,group A,associate's degree,free/reduced,none,47,57,44,3,71
4,male,group C,some college,standard,none,76,78,75,4,41
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995,39
996,male,group C,high school,free/reduced,none,62,55,55,996,85
997,female,group C,high school,free/reduced,completed,59,71,65,997,27
998,female,group D,some college,standard,completed,68,78,77,998,45
999,female,group D,some college,free/reduced,none,77,86,86,999,12

In [65]:
np.random.uniform(1,100,size =1000) #float numbers

array([66.36600896, 13.52062805,  3.45874614, 69.70131754, 61.0824808 ,
       92.37162895, 47.92464812, 66.55282281, 58.91927969, 74.08580956,
       35.13722347,  2.87281993, 10.33454225, 78.07667234, 77.33630684,
       28.46205586,  7.31513759, 66.54809119, 43.16166994, 96.6588707 ,
       87.84393285, 89.23510928, 62.71529862, 41.50313451, 73.00898723,
       62.33958362, 16.65328991, 43.94716538, 19.53714717, 68.77521813,
       15.47885411, 72.99382824,  9.30613196, 79.68799386, 24.98472099,
       47.76444595, 90.56056245, 18.63260156, 54.00946533, 19.0900465 ,
       38.44525434, 54.14981044, 60.6783828 , 53.96409895, 34.30169328,
       74.1669551 , 81.36664896, 39.9617211 , 91.32207874, 76.85896442,
       13.33871853, 93.91224559, 80.55945609, 14.58153197, 17.7354294 ,
       36.96910367, 66.10298026, 70.24569051, 68.60015085, 13.56030569,
       20.82921143, 18.38528625, 77.92602309, 35.0951754 , 48.76906357,
       39.2355022 , 70.28110655, 72.29163666, 13.5156347 , 79.9939028 ,
        5.05352004, 93.41417301, 94.86696937, 95.38631695, 77.04943545,
       57.94645768, 22.13105306, 57.67312641, 46.81860533, 34.28077041,
       24.88204381,  6.78153425, 11.84119549, 60.13245596, 55.10358108,
       89.34327788, 39.04709475, 57.38988517, 32.03463424, 74.95184889,
       26.55888593, 22.26112035, 35.74463253, 36.50523863,  2.03490845,
       56.21663706, 66.29325282, 93.03011036, 68.70301233, 68.55556483,
       67.55812381, 78.43281907, 67.52769621, 25.91888067, 74.29613162,
       94.99101045, 29.80551094, 32.44461654, 42.12565969, 58.69350993,
       26.67047112, 82.42244203, 38.88649255, 77.94286211, 39.11725275,
       59.96648275, 55.77074313, 71.37366868, 98.25153417,  4.78520338,
       91.26412571, 61.27351996, 10.00654812, 12.17497686, 62.20575987,
       32.63660166, 54.21984556, 42.12047626, 84.34120572, 35.3815331 ,
       36.2671071 , 58.58875417, 51.55541633, 28.6628185 , 37.26042252,
       69.86413208, 67.18436087, 15.30831024, 66.82518474, 32.38298516,
       10.89451132, 21.45918876, 27.606617  , 81.19774225, 58.59162842,
       90.92129766, 69.87119708, 79.38235652, 19.35753666, 52.71236959,
       89.26410501, 56.47517049, 87.6668822 , 32.35310266, 73.59022463,
       29.76877967, 36.11014612, 70.78552229, 90.45807232, 63.36026883,
       12.07152804, 93.61770195, 85.34816407, 37.00892214,  5.58692821,
       65.66091569, 71.00822045, 55.27462642, 94.3006856 , 60.63273501,
       89.20337557, 89.29270921, 89.14905849, 98.77047563, 19.82416138,
       74.05217906, 41.49049237, 12.40416519, 79.85806426,  2.52706156,
       36.04964121, 34.68364186, 41.25801424, 11.05591341, 81.21746487,
        5.73565274, 68.98387972, 88.69297758, 96.37827742, 16.1726776 ,
       49.8609054 , 63.75523387, 78.23981404, 31.23327043, 99.51012557,
       97.17288335, 88.4924043 , 24.53158688, 14.17641732, 79.32777518,
       60.32616287, 34.43476976, 25.18353839, 13.70577193, 31.26158699,
       55.03235246, 89.63724233, 75.81758977, 28.56220081, 38.45341049,
       58.82807623, 97.34143483, 36.37629976, 86.14577818, 43.23586728,
       87.18867671, 57.73859881, 96.05407327, 86.9576357 , 74.1799462 ,
        9.57487374, 97.13065361, 66.41793034, 41.0344239 , 72.76714342,
       74.73955008, 18.46727381, 38.60560051, 49.00465706, 82.87048928,
       75.86964433,  3.31282394,  7.49014239, 10.34234413, 63.00974854,
       44.79029064, 15.46138053, 43.62239204, 64.85410137, 28.51127627,
       89.91241092,  4.63135166,  7.43260205, 91.85294929, 30.72521366,
       34.87221572, 63.88012362, 19.50650346, 88.47252976, 74.39735714,
       23.69073151, 36.29168589, 10.75824399, 49.56995413, 40.05155224,
       31.91833246, 76.97938911, 32.31745273, 44.31640967, 92.11392456,
       66.78079345,  9.60458586, 16.7881517 , 57.23215362, 45.22020902,
       16.3318541 , 12.81596917, 34.67981458, 89.69735167, 64.6804751 ,
       18.54818396, 27.0991233 , 57.57048421, 11.6420548 , 18.06534797,
       57.76150633, 81.47288005, 25.0612123 , 88.37646922, 16.3644014 ,
       71.72537518, 73.12535709, 60.10910609, 20.12704226, 89.34842359,
       71.28555921, 23.94163268, 55.6461782 , 91.38495844, 47.72034109,
       37.11629229, 27.31613748, 67.63984178, 36.26193897, 90.4435645 ,
       62.97383237, 26.14962641, 46.24360128, 17.76569919, 95.54853741,
        9.10387261, 31.76469571, 42.76775521, 33.78042297, 66.62655324,
       22.11814511, 31.12201585, 64.72818576, 81.02861741, 59.58589965,
       64.55485307, 30.90403896, 83.28856288, 47.56207047, 51.50481786,
       42.03169891, 16.83951275,  4.94100933, 37.92929112, 37.79645529,
       86.32044288, 12.23236364, 34.19283435, 22.88664345,  6.49370083,
       34.43509114, 20.22421718, 54.53452306, 40.08088334, 51.03868491,
       37.57255212, 63.98349221, 44.42809173, 19.57601113, 69.88730343,
       66.78171876, 13.63329575, 67.78875748, 67.2714714 ,  1.88168521,
       47.33820953, 83.82466774, 98.11659861, 75.33052356, 49.03748195,
       66.00640704, 86.13905322, 85.70306819, 73.46921625, 23.25384378,
       25.28602439, 27.44553828, 73.68565519, 94.88221927, 27.61117076,
        5.83571371, 80.89965796, 33.19891311, 13.26168375, 24.45082242,
       17.76085712, 96.10263   , 24.92110063, 31.72505465, 22.84812364,
       31.81371639, 88.05574427, 52.40509827, 13.48744624, 90.74527824,
       24.39862157, 56.20236879, 15.26867493, 69.41233863, 84.41610648,
       25.14833859, 65.99359633, 49.28537485, 59.08361354, 51.77062055,
       19.41139753, 27.94105871, 39.04176051, 70.41197871, 79.94385057,
       26.18854343, 94.25839811, 74.34084734, 32.89677511, 14.80932911,
        4.8578505 ,  1.25603804, 92.96222326, 77.53102333, 19.26439413,
       14.73386977, 69.34978907, 24.20416446, 76.31906204, 50.78257782,
       45.58829649,  9.86563499, 96.00143173, 10.47940682, 95.7692093 ,
       50.35384191, 67.7522831 , 64.53491208, 83.9506384 ,  3.21050799,
       60.35568372, 25.99310133, 98.03878547, 23.1625716 , 78.8607801 ,
       74.62703152, 96.43892645, 74.64149923, 63.32250491, 78.51744313,
       76.3487972 , 81.49358589,  3.04387195, 97.98510807, 51.52705671,
       88.43255156, 26.10139015, 61.95844445, 56.23223901, 77.68642757,
       28.34352126, 72.05079749, 42.6682936 , 96.01858673, 37.09826727,
       68.17529829, 90.33686383, 73.16588166, 45.71040884, 92.18787335,
       20.31481849, 87.20911824, 42.24882623, 31.37912048, 46.46163118,
       74.72078614, 78.4333472 , 99.22563131, 17.89408324, 47.29698975,
       62.64198663,  8.61384227, 74.27927783, 17.90300966, 54.01366412,
       80.13781037, 31.58515976, 77.84105135, 45.13344478, 19.46890294,
       72.26005467, 78.57713723, 65.46966955, 51.02818321, 10.18137518,
        7.021861  , 24.10271063, 87.86069435,  3.8222538 , 60.14356077,
       80.61336838, 79.34094687, 66.272705  , 55.20450306, 54.68848213,
       74.36272262, 24.08179201,  7.04016523, 25.58010584, 96.08495149,
       64.97661194, 77.75105059, 73.61912374, 32.02921171, 28.07857904,
       13.92487711, 99.41135711, 23.96182421,  8.2235153 , 44.44462001,
       93.14429356, 44.83973586, 88.90769993, 36.62463189, 44.48632757,
        7.78652147, 73.92241242, 49.64827567, 86.47953595, 83.52043166,
       63.72203293,  9.53032353, 13.67577271, 49.81348372, 40.75531696,
       49.98903425, 73.96690394, 87.10358194, 73.16927755, 52.76889758,
       78.40966126, 12.35248464, 71.22726514, 87.55564897, 34.43397019,
       26.13563866, 62.79844559, 10.75472185, 59.43908952, 34.2758223 ,
       64.9492004 , 69.57135554, 67.00132554, 52.01456389, 70.01140948,
       47.73781509, 27.22062687, 17.13327918,  6.70435004, 33.95451752,
       88.38214181,  7.82672325, 76.9966426 , 25.47662559, 17.54556612,
       35.13060647, 34.78814503, 64.6437296 , 48.85754828, 73.01194493,
        5.86741724, 28.86384815, 75.46647277, 84.05865607, 83.08517573,
       57.32553838, 38.85528977, 53.60931533, 41.34413283, 45.92243888,
       34.93770095,  7.82206504, 20.83555122, 75.82031219, 89.60133189,
        4.00113035, 28.76047593, 59.81017211, 10.852207  , 81.72715983,
       47.16972583,  3.35307354, 22.86401943, 96.39031689, 73.01666297,
       45.4534508 , 36.38495775, 15.19557274,  4.6745588 , 19.33750712,
       54.78988703, 14.4931807 , 58.98921595, 15.74125225, 95.85731205,
       62.54628048, 55.29771241,  3.97602128, 42.0552628 , 94.82976487,
       85.35751188, 61.67414604, 12.16378547, 29.52085935, 80.81038585,
       69.97784889, 74.06276422, 66.92810016, 88.93761457, 98.43116226,
       28.64943011, 69.48390771, 64.50868586, 31.63502256, 41.40531392,
        7.26736797, 12.61907567, 18.03141699, 93.57732468, 34.76424896,
       33.64831672, 85.64713735, 43.37266199, 72.9857832 ,  3.36754101,
       62.07138198, 59.78312893, 83.40057613, 90.73384751, 32.65983394,
       46.538837  ,  3.09141201, 33.62571764, 74.08267884, 63.90307941,
        1.30712937, 56.48514838,  9.65787655, 19.09161614, 58.74503329,
       56.97682316, 79.90967461, 31.19597959, 46.5601561 , 16.90336875,
       40.56538648, 66.00948404, 12.38787628, 30.31071541, 93.38175345,
       74.90216563, 19.56248133, 50.77159476, 85.38418934, 10.00565852,
       13.98540221, 58.60818232, 41.89274711, 69.45564711, 17.63883951,
       65.83986243, 74.25189245, 60.84211154, 19.69487866, 76.46383833,
        7.29669219, 88.71441629, 71.20077831, 62.75803973, 29.63128362,
       23.85647152, 94.17951292, 24.66252985, 34.71812112, 97.27334853,
       71.77579485, 95.70983177, 72.82960565,  9.42888376, 49.64732167,
       45.83004232, 65.11360426, 43.79410861, 23.62992139,  5.48598896,
       26.69845935, 56.97535542, 25.13102668, 12.91923413, 68.55056074,
       92.0058964 , 26.22995527, 73.13661851, 56.44009971,  6.61388025,
       24.36083652, 58.54665553, 13.07349676, 65.72048655, 21.76328671,
       66.35902433, 16.41494048, 79.35214077, 81.31553675, 14.64797323,
       94.62108302, 21.03772169, 86.35068379, 79.9429556 , 24.68284423,
       96.63887156, 52.83139137, 75.54745637, 20.1567389 , 42.51095674,
       76.77378818, 38.3282126 , 81.23303899, 21.07828736, 13.97435883,
       40.72578341, 59.24625822, 90.64427017, 90.69353562, 83.67491594,
       57.65245242, 90.89223423,  8.31404749,  5.44127227, 88.56529655,
       71.42848023, 93.17632463, 69.2054354 , 17.85771588, 14.88341949,
       80.26583803, 39.47491781, 85.69652194, 67.76056851,  3.91021215,
       15.06632226, 84.35094845, 13.84114698, 37.46088004, 35.05178269,
       54.39815697, 52.49473272, 17.6280259 , 52.89450247, 95.14118238,
       72.34058371,  7.5695913 , 75.96352816, 39.17213367, 23.24264434,
       50.62211758, 69.39486669, 98.83007764, 70.08834651, 45.66028919,
       90.7345507 , 42.70291911, 68.83570699, 53.54894097, 51.56798277,
       45.45013351, 56.37811124,  3.0182191 , 88.05798402, 40.38826166,
       35.58264471, 29.28161734,  5.76384131, 96.3865219 , 29.17166862,
       38.69158503, 46.66486144, 86.56304201, 26.56163672, 93.7873142 ,
       93.46257848, 79.77143446, 91.55011136, 49.00855185, 29.3739871 ,
        7.16127209, 82.57042297, 66.20192878, 80.16392741, 83.88748823,
       47.73289021, 17.89080169, 91.24896302, 80.23884778, 45.70289659,
       26.32954515, 42.18047114, 41.53149938, 38.85474695, 60.72854961,
       57.66549354, 41.65297376, 69.18876868, 59.60704212,  6.75358976,
       80.21539292, 58.11643048, 15.76404462, 44.855895  , 67.25759874,
        4.76542009, 62.45636164, 58.65171804, 15.2625641 , 27.98085419,
       15.70667415, 11.66735035, 39.71900316, 56.87381763, 73.97522229,
       23.34919393, 71.67778948, 26.74170718, 73.13384092, 62.79321522,
       50.7569412 , 79.29559078, 21.0596734 , 90.47250926, 76.43910983,
       97.46540993, 37.57279659,  3.66408378, 33.06987261, 16.81581742,
       90.44340512, 13.36542029, 44.86234385, 46.10854992, 22.27601482,
       26.26635005, 59.97883132, 90.37426654, 41.80363509, 32.16098458,
       21.4615635 , 98.50537963, 96.83043941, 34.49322374, 10.53482072,
       20.69957179, 75.43561427, 58.20582306, 91.8927349 , 13.49054113,
       53.79525029, 69.30137623, 24.9438472 , 55.61174061, 99.56735584,
       16.2680084 , 61.55851956, 64.34988311, 38.22920235, 88.77514591,
       43.61426686, 35.35391971, 78.85208528, 66.2408329 ,  8.91122218,
       41.62380834, 94.03918348, 48.9864114 ,  1.10617439, 97.89864167,
       69.82988358, 60.2761288 , 46.81223722, 79.91452593,  4.95587147,
       97.02551619, 18.61462365,  6.75647643,  1.68817599, 55.08051653,
       91.17801642, 89.28569885, 84.71212882, 85.89296153, 52.0424484 ,
       57.60708205, 67.39073877, 72.08798344, 14.94106179, 65.92115562,
       76.6193124 , 91.19367112, 98.36952612, 47.62167424, 47.97157356,
       16.12788797, 22.77602179, 87.54236962, 15.30705428, 96.05947736,
       23.39920579, 55.29324461,  8.90952134, 18.70755714, 35.18567442,
       26.27660176, 58.76156985, 42.71701036, 16.29669177, 58.90722381,
       51.67606242, 83.34872687, 75.27829926, 87.74606338, 79.18854489,
       30.05500531, 86.70311   , 29.74347051, 10.88016744, 25.82901449,
       34.3454965 , 84.40467663, 95.65263005, 18.88099147, 21.24533185,
       25.83248329, 94.46523663, 25.63143186, 87.19250431, 84.02040607,
       54.83621409, 74.84908999, 27.6233241 , 43.88801282, 21.70442084,
       24.17715236,  4.97411881, 94.6538197 , 65.31168721, 69.45149568,
        4.67946723, 20.57976244, 76.08544979, 69.01257096, 39.16138395,
       93.43477877, 12.4069642 , 88.81412194, 95.54865742, 63.71771367,
       44.56379373, 69.28559175, 47.79344583, 62.07036312, 72.44329486,
       10.19296461, 40.31891885,  1.54605129, 53.24441439,  9.93452645,
       36.83826901, 29.9154073 , 58.17896339, 76.42887638,  9.21940922,
       71.12905407, 57.33448862, 86.69137462, 72.82868468,  8.00672993,
       68.47628884, 72.09224235, 81.34666941, 13.08026355, 77.33943803,
        4.76877089, 17.76927618, 31.18447894,  6.92432801, 79.01348392,
       97.63440984, 48.18307548, 46.65235359, 44.45377172, 47.71278618,
       54.25756529,  9.78280651, 85.24692827, 54.03994162, 16.06129915,
       82.26977067, 83.1835163 , 31.59989592, 26.31160986,  2.21255513,
       72.95875116, 28.3701317 , 23.86432192, 69.16148726, 78.15421086,
       92.44347792, 55.88889142, 17.39765267, 12.34353084, 86.319563  ,
       61.8826193 , 81.39055632, 36.08883272, 12.55593464, 17.36920088,
       72.09373858, 68.12091467, 99.56190355, 27.00788125, 70.24971408])

Adding a new column

assign()
add muliple columns in a single line of code
when you need to overwrite values of existing columns (best practice)
it returns a new object(a copy) with all the original columns in addition to new ones

In [66]:
score1 = np.random.randint(1,100,size=1000)
score2 = np.random.randint(1,100,size=1000)

#create series now using the above random numbers
series1 = pd.Series(score1, index=np.arange(0,1000))
series2 = pd.Series(score2, index=np.arange(0,1000))
#using assign to add multiple columns
df_exams.assign(newcol1=series1,newcol2=series2) #copy only not the original 

#df_exams = df_exams.assign(newcol1=series1,newcol2=series2) #updates the original

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score,newcol1,newcol2
0,female,group B,bachelor's degree,standard,none,72,72,74,0,83,38,56
1,female,group C,some college,standard,completed,69,90,88,1,90,46,9
2,female,group B,master's degree,standard,none,90,95,93,2,44,68,9
3,male,group A,associate's degree,free/reduced,none,47,57,44,3,71,48,4
4,male,group C,some college,standard,none,76,78,75,4,41,50,12
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995,39,78,60
996,male,group C,high school,free/reduced,none,62,55,55,996,85,55,63
997,female,group C,high school,free/reduced,completed,59,71,65,997,27,51,10
998,female,group D,some college,standard,completed,68,78,77,998,45,87,39
999,female,group D,some college,free/reduced,none,77,86,86,999,12,83,62

insert()

insert a new column at a specific position or index
does not create a copy , updates the original

In [68]:
#using index to add a column
df_exams.insert(1,'test',series1)

In [69]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score
0,female,38,group B,bachelor's degree,standard,none,72,72,74,0,83
1,female,46,group C,some college,standard,completed,69,90,88,1,90
2,female,68,group B,master's degree,standard,none,90,95,93,2,44
3,male,48,group A,associate's degree,free/reduced,none,47,57,44,3,71
4,male,50,group C,some college,standard,none,76,78,75,4,41
...,...,...,...,...,...,...,...,...,...,...,...
995,female,78,group E,master's degree,standard,completed,88,99,95,995,39
996,male,55,group C,high school,free/reduced,none,62,55,55,996,85
997,female,51,group C,high school,free/reduced,completed,59,71,65,997,27
998,female,87,group D,some college,standard,completed,68,78,77,998,45
999,female,83,group D,some college,free/reduced,none,77,86,86,999,12

Operations on DataFrames

Math Operations

In [70]:
totalsum = sum(df_exams['test']) #or .sum() 
totalsum

50399

In [72]:
#count , min ,max ,std,mean
meanv = df_exams['math score'].mean()
avg = df_exams['math score'].sum() / df_exams['math score'].count()
stD  = df_exams['math score'].std()#standard deviation

print(f" {meanv}  {avg}  {stD} ")

 66.089  66.089  15.163080096009468

In [73]:
df_exams.describe() #gives all details as well

,test,math score,reading score,writing score,language score,language_score
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000
mean,50.399000,66.08900,69.169000,68.054000,499.500000,49.367000
std,28.184467,15.16308,14.600192,15.195657,288.819436,28.342576
min,1.000000,0.00000,17.000000,10.000000,0.000000,1.000000
25%,27.000000,57.00000,59.000000,57.750000,249.750000,25.000000
50%,51.000000,66.00000,70.000000,69.000000,499.500000,49.000000
75%,75.000000,77.00000,79.000000,79.000000,749.250000,74.000000
max,99.000000,100.00000,100.000000,100.000000,999.000000,99.000000

Operations in rows

In [74]:
#calculating sum in a row for all rows
df_exams['test'] + df_exams['math score']

0      110
1      115
2      158
3       95
4      126
      ...
995    166
996    117
997    110
998    155
999    160
Length: 1000, dtype: int64

In [75]:
#calculating average scores of test and math score column
df_exams['average']  =  (df_exams['test'] + df_exams['math score'])/2
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score,average
0,female,38,group B,bachelor's degree,standard,none,72,72,74,0,83,55.0
1,female,46,group C,some college,standard,completed,69,90,88,1,90,57.5
2,female,68,group B,master's degree,standard,none,90,95,93,2,44,79.0
3,male,48,group A,associate's degree,free/reduced,none,47,57,44,3,71,47.5
4,male,50,group C,some college,standard,none,76,78,75,4,41,63.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,78,group E,master's degree,standard,completed,88,99,95,995,39,83.0
996,male,55,group C,high school,free/reduced,none,62,55,55,996,85,58.5
997,female,51,group C,high school,free/reduced,completed,59,71,65,997,27,55.0
998,female,87,group D,some college,standard,completed,68,78,77,998,45,77.5
999,female,83,group D,some college,free/reduced,none,77,86,86,999,12,80.0

Value counts method

counts by category as well

In [77]:
#counting gender by category
df_exams['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [78]:
#return the relative freq (divide all values by sum of values)
df_exams['gender'].value_counts(normalize=True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [79]:
#counting parental level of education by category
df_exams['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [80]:
df_exams['parental level of education'].value_counts(normalize=True).round(2)

parental level of education
some college          0.23
associate's degree    0.22
high school           0.20
some high school      0.18
bachelor's degree     0.12
master's degree       0.06
Name: proportion, dtype: float64

Sort a dataframe

In [81]:
#sort by 1 column
#creates a copy of dataframe does not update the original
df_exams.sort_values(by='math score')

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score,average
59,female,43,group C,some high school,free/reduced,none,0,17,10,59,11,21.5
980,female,75,group B,high school,free/reduced,none,8,24,23,980,22,41.5
17,female,28,group B,some high school,free/reduced,none,18,32,28,17,42,23.0
787,female,97,group B,some college,standard,none,19,38,32,787,49,58.0
145,female,74,group C,some college,free/reduced,none,22,39,33,145,87,48.0
...,...,...,...,...,...,...,...,...,...,...,...,...
625,male,27,group D,some college,standard,completed,100,97,99,625,79,63.5
623,male,99,group A,some college,standard,completed,100,96,86,623,69,99.5
451,female,87,group E,some college,standard,none,100,92,97,451,30,93.5
962,female,5,group E,associate's degree,standard,none,100,100,100,962,18,52.5
149,male,4,group E,associate's degree,free/reduced,completed,100,100,93,149,69,52.0

In [82]:
#sort by 1 column descending

df_exams.sort_values(by='math score',ascending = False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score,average
962,female,5,group E,associate's degree,standard,none,100,100,100,962,18,52.5
625,male,27,group D,some college,standard,completed,100,97,99,625,79,63.5
458,female,37,group E,bachelor's degree,standard,none,100,100,100,458,8,68.5
623,male,99,group A,some college,standard,completed,100,96,86,623,69,99.5
451,female,87,group E,some college,standard,none,100,92,97,451,30,93.5
...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,74,group C,some college,free/reduced,none,22,39,33,145,87,48.0
787,female,97,group B,some college,standard,none,19,38,32,787,49,58.0
17,female,28,group B,some high school,free/reduced,none,18,32,28,17,42,23.0
980,female,75,group B,high school,free/reduced,none,8,24,23,980,22,41.5
59,female,43,group C,some high school,free/reduced,none,0,17,10,59,11,21.5

In [83]:
#sort by multiple columns descending

df_exams.sort_values(by=['math score','reading score'],ascending = False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score,average
149,male,4,group E,associate's degree,free/reduced,completed,100,100,93,149,69,52.0
458,female,37,group E,bachelor's degree,standard,none,100,100,100,458,8,68.5
916,male,98,group E,bachelor's degree,standard,completed,100,100,100,916,37,99.0
962,female,5,group E,associate's degree,standard,none,100,100,100,962,18,52.5
625,male,27,group D,some college,standard,completed,100,97,99,625,79,63.5
...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,74,group C,some college,free/reduced,none,22,39,33,145,87,48.0
787,female,97,group B,some college,standard,none,19,38,32,787,49,58.0
17,female,28,group B,some high school,free/reduced,none,18,32,28,17,42,23.0
980,female,75,group B,high school,free/reduced,none,8,24,23,980,22,41.5
59,female,43,group C,some high school,free/reduced,none,0,17,10,59,11,21.5

In [84]:
#inplace = True means update the original data frame not the copy
df_exams.sort_values(by=['math score','reading score'],ascending = False,inplace=True)

In [85]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score,average
149,male,4,group E,associate's degree,free/reduced,completed,100,100,93,149,69,52.0
458,female,37,group E,bachelor's degree,standard,none,100,100,100,458,8,68.5
916,male,98,group E,bachelor's degree,standard,completed,100,100,100,916,37,99.0
962,female,5,group E,associate's degree,standard,none,100,100,100,962,18,52.5
625,male,27,group D,some college,standard,completed,100,97,99,625,79,63.5
...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,74,group C,some college,free/reduced,none,22,39,33,145,87,48.0
787,female,97,group B,some college,standard,none,19,38,32,787,49,58.0
17,female,28,group B,some high school,free/reduced,none,18,32,28,17,42,23.0
980,female,75,group B,high school,free/reduced,none,8,24,23,980,22,41.5
59,female,43,group C,some high school,free/reduced,none,0,17,10,59,11,21.5

In [86]:
#sort descending with a key function
df_exams.sort_values(by=['race/ethnicity'],ascending = True, key = lambda col : col.str.lower() ) #get a string value and get lower case

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score,average
741,female,97,group A,associate's degree,free/reduced,none,37,57,56,741,97,67.0
151,male,46,group A,bachelor's degree,standard,none,77,67,68,151,38,61.5
811,male,21,group A,high school,free/reduced,none,45,47,49,811,9,33.0
112,male,21,group A,associate's degree,standard,none,54,53,47,112,56,37.5
25,male,78,group A,master's degree,free/reduced,none,73,74,72,25,12,75.5
...,...,...,...,...,...,...,...,...,...,...,...,...
751,male,54,group E,some college,standard,none,68,72,65,751,78,61.0
915,female,61,group E,some college,standard,none,68,70,66,915,58,64.5
592,male,19,group E,bachelor's degree,standard,none,68,68,64,592,51,43.5
479,male,6,group E,associate's degree,standard,none,76,71,67,479,26,41.0
517,female,79,group E,some college,standard,completed,66,74,73,517,35,72.5

set_index() and sort_index methods

In [87]:
import random

In [90]:
# creating non repetitive values for the index
new_index = np.arange(0,1000)

#shuffling the indexes
random.shuffle(new_index)

#create a new column with new index
df_exams['new_index'] = new_index
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score,average,new_index
149,male,4,group E,associate's degree,free/reduced,completed,100,100,93,149,69,52.0,569
458,female,37,group E,bachelor's degree,standard,none,100,100,100,458,8,68.5,678
916,male,98,group E,bachelor's degree,standard,completed,100,100,100,916,37,99.0,305
962,female,5,group E,associate's degree,standard,none,100,100,100,962,18,52.5,338
625,male,27,group D,some college,standard,completed,100,97,99,625,79,63.5,323
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,74,group C,some college,free/reduced,none,22,39,33,145,87,48.0,908
787,female,97,group B,some college,standard,none,19,38,32,787,49,58.0,436
17,female,28,group B,some high school,free/reduced,none,18,32,28,17,42,23.0,161
980,female,75,group B,high school,free/reduced,none,8,24,23,980,22,41.5,213
59,female,43,group C,some high school,free/reduced,none,0,17,10,59,11,21.5,980

SET INDEX

In [91]:
#set new_index column as index creates a copy and return it
df_exams.set_index('new_index')

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score,average
new_index,,,,,,,,,,,,
569,male,4,group E,associate's degree,free/reduced,completed,100,100,93,149,69,52.0
678,female,37,group E,bachelor's degree,standard,none,100,100,100,458,8,68.5
305,male,98,group E,bachelor's degree,standard,completed,100,100,100,916,37,99.0
338,female,5,group E,associate's degree,standard,none,100,100,100,962,18,52.5
323,male,27,group D,some college,standard,completed,100,97,99,625,79,63.5
...,...,...,...,...,...,...,...,...,...,...,...,...
908,female,74,group C,some college,free/reduced,none,22,39,33,145,87,48.0
436,female,97,group B,some college,standard,none,19,38,32,787,49,58.0
161,female,28,group B,some high school,free/reduced,none,18,32,28,17,42,23.0
213,female,75,group B,high school,free/reduced,none,8,24,23,980,22,41.5
980,female,43,group C,some high school,free/reduced,none,0,17,10,59,11,21.5

In [96]:
df_exams.set_index('new_index', inplace = True) #changes the original

Sort Index

In [97]:
#sort dataframe by new index
df_exams.sort_index()

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score,average
new_index,,,,,,,,,,,,
0,female,99,group C,some high school,free/reduced,none,48,56,51,929,34,73.5
1,female,22,group E,associate's degree,standard,completed,82,85,86,56,26,52.0
2,male,94,group C,high school,free/reduced,none,27,34,36,91,10,60.5
3,male,39,group D,bachelor's degree,free/reduced,completed,74,71,80,24,71,56.5
4,male,89,group D,high school,standard,none,41,52,51,640,49,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,19,group B,master's degree,free/reduced,completed,52,70,62,178,87,35.5
996,male,75,group D,some college,standard,none,40,42,38,33,7,57.5
997,female,52,group B,high school,standard,none,65,64,62,248,98,58.5
998,female,91,group C,high school,standard,none,75,88,85,633,39,83.0
999,male,61,group C,some college,standard,none,73,74,61,668,2,67.0

In [99]:
#sort in descending
df_exams.sort_index(ascending=False)
# in place
#df_exams.sort_index(ascending=False,inplace=True)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score,average
new_index,,,,,,,,,,,,
999,male,61,group C,some college,standard,none,73,74,61,668,2,67.0
998,female,91,group C,high school,standard,none,75,88,85,633,39,83.0
997,female,52,group B,high school,standard,none,65,64,62,248,98,58.5
996,male,75,group D,some college,standard,none,40,42,38,33,7,57.5
995,female,19,group B,master's degree,free/reduced,completed,52,70,62,178,87,35.5
...,...,...,...,...,...,...,...,...,...,...,...,...
4,male,89,group D,high school,standard,none,41,52,51,640,49,65.0
3,male,39,group D,bachelor's degree,free/reduced,completed,74,71,80,24,71,56.5
2,male,94,group C,high school,free/reduced,none,27,34,36,91,10,60.5
1,female,22,group E,associate's degree,standard,completed,82,85,86,56,26,52.0
0,female,99,group C,some high school,free/reduced,none,48,56,51,929,34,73.5

RENAME COLUMN

In [100]:
#rename column and overwirte values of the dataframe
df_exams.rename(columns={'gender':'Gender'})

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score,average
new_index,,,,,,,,,,,,
569,male,4,group E,associate's degree,free/reduced,completed,100,100,93,149,69,52.0
678,female,37,group E,bachelor's degree,standard,none,100,100,100,458,8,68.5
305,male,98,group E,bachelor's degree,standard,completed,100,100,100,916,37,99.0
338,female,5,group E,associate's degree,standard,none,100,100,100,962,18,52.5
323,male,27,group D,some college,standard,completed,100,97,99,625,79,63.5
...,...,...,...,...,...,...,...,...,...,...,...,...
908,female,74,group C,some college,free/reduced,none,22,39,33,145,87,48.0
436,female,97,group B,some college,standard,none,19,38,32,787,49,58.0
161,female,28,group B,some high school,free/reduced,none,18,32,28,17,42,23.0
213,female,75,group B,high school,free/reduced,none,8,24,23,980,22,41.5
980,female,43,group C,some high school,free/reduced,none,0,17,10,59,11,21.5

In [102]:
#replace multiple columns and update the dataframe with inplace argument
df_exams.rename(columns={'math score':'MS','reading score':'RS','writing score':'WS'},inplace=True)

Rename Index

In [ ]:
#rename index 0,1,2 and update the dataframe
df_exams.renmae(index={0:'A',1:'B',2:'C'})