In [1]:
import pandas as pd

1 Read a .csv file from a URL with pandas

In [3]:
#reading 1 csv file from the web
#https://www.football-data.co.uk/mmz4281/2526/E0.csv
df_premier25 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2526/E0.csv')

In [4]:
#renaming columns
df_premier25.rename(columns={'FTHG':'home_goals','FTAG' : 'away_goals'},inplace=True)

In [5]:
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,E0,17/05/2026,15:00,Everton,Sunderland,1,3,A,1,0,...,1.80,2.05,NaN,NaN,1.87,2.05,1.79,1.94,1.90,2.09
364,E0,17/05/2026,15:00,Leeds,Brighton,1,0,H,0,0,...,1.75,2.05,NaN,NaN,1.81,2.05,1.75,1.98,1.86,2.14
365,E0,17/05/2026,15:00,Wolves,Fulham,1,1,D,1,1,...,2.03,1.83,NaN,NaN,2.03,1.87,1.93,1.80,2.11,1.88
366,E0,17/05/2026,17:30,Newcastle,West Ham,3,1,H,2,0,...,2.05,1.80,NaN,NaN,2.05,1.80,2.00,1.74,2.12,1.87
367,E0,18/05/2026,20:00,Arsenal,Burnley,1,0,H,1,0,...,1.88,1.98,NaN,NaN,1.88,1.98,1.83,1.89,1.94,2.05

2 Read a .csv file from Multiple URLs with pandas

LINK : root + season + league + .csv

In [6]:
# https://www.football-data.co.uk/mmz4281/2526/E0.csv
# https://www.football-data.co.uk/mmz4281/2526/E1.csv
# https://www.football-data.co.uk/mmz4281/2526/E2.csv
# https://www.football-data.co.uk/mmz4281/2526/E3.csv
# https://www.football-data.co.uk/mmz4281/2526/EC.csv

#create a root variable 
root = 'https://www.football-data.co.uk/mmz4281/'
season = '2526/'

#creating a list of leagues
leagues = ['E0','E1','E2','E3','EC']
frames  = [] #list of dataframes
for league in leagues:
    df = pd.read_csv(root + season + league + '.csv' , encoding='unicode_escape')
    frames.append(df)

In [7]:
#length of frames
len(frames)

5

In [9]:
frames[0] #get first data frame

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,E0,17/05/2026,15:00,Everton,Sunderland,1,3,A,1,0,...,1.80,2.05,NaN,NaN,1.87,2.05,1.79,1.94,1.90,2.09
364,E0,17/05/2026,15:00,Leeds,Brighton,1,0,H,0,0,...,1.75,2.05,NaN,NaN,1.81,2.05,1.75,1.98,1.86,2.14
365,E0,17/05/2026,15:00,Wolves,Fulham,1,1,D,1,1,...,2.03,1.83,NaN,NaN,2.03,1.87,1.93,1.80,2.11,1.88
366,E0,17/05/2026,17:30,Newcastle,West Ham,3,1,H,2,0,...,2.05,1.80,NaN,NaN,2.05,1.80,2.00,1.74,2.12,1.87
367,E0,18/05/2026,20:00,Arsenal,Burnley,1,0,H,1,0,...,1.88,1.98,NaN,NaN,1.88,1.98,1.83,1.89,1.94,2.05

In [10]:
frames[4] #get last data frame

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,EC,25/04/2026,12:30,Scunthorpe,Eastleigh,0,1,A,0,1,...,1.85,1.95,NaN,NaN,1.85,1.95,1.80,1.88,NaN,NaN
548,EC,25/04/2026,12:30,Southend,Wealdstone,2,1,H,2,1,...,1.83,1.98,NaN,NaN,1.83,1.98,1.78,1.91,NaN,NaN
549,EC,25/04/2026,12:30,Tamworth,Braintree Town,5,1,H,2,1,...,1.78,2.03,NaN,NaN,1.83,2.03,1.77,1.93,NaN,NaN
550,EC,25/04/2026,12:30,Woking,Halifax,0,1,A,0,0,...,2.08,1.73,NaN,NaN,2.08,1.75,1.99,1.72,NaN,NaN
551,EC,25/04/2026,12:30,Yeovil,Solihull,1,4,A,1,4,...,1.78,2.03,NaN,NaN,1.78,2.03,1.73,1.97,NaN,NaN

In [11]:
# https://www.football-data.co.uk/mmz4281/2526/E0.csv
# https://www.football-data.co.uk/mmz4281/2526/E1.csv
# https://www.football-data.co.uk/mmz4281/2526/E2.csv
# https://www.football-data.co.uk/mmz4281/2526/E3.csv
# https://www.football-data.co.uk/mmz4281/2526/EC.csv

#create a root variable 
root = 'https://www.football-data.co.uk/mmz4281/'

#creating a list of leagues
leagues = ['E0','E1','E2']
frames  = [] #list of dataframes
for league in leagues:
    for season in range(20,26):
        
        df = pd.read_csv(root + str(season) + str(season+1)  + '/' + league + '.csv' , encoding='unicode_escape')
        #add a new column indicating which season is in dataframe
        df.insert(1,'season', str(season))
        frames.append(df)

In [12]:
len(frames) # 6 season x 3 leagues

18

In [13]:
frames[0]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,20,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,...,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87
1,E0,20,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,...,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12
2,E0,20,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,...,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04
3,E0,20,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,...,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86
4,E0,20,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,...,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,20,23/05/2021,16:00,Liverpool,Crystal Palace,2,0,H,1,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,E0,20,23/05/2021,16:00,Man City,Everton,5,0,H,2,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,E0,20,23/05/2021,16:00,Sheffield United,Burnley,1,0,H,1,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,E0,20,23/05/2021,16:00,West Ham,Southampton,3,0,H,2,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,E0,20,23/05/2021,16:00,Wolves,Man United,1,2,A,1,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88

In [14]:
frames[17]

,ï»¿Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E2,25,01/08/2025,20:00,Luton,AFC Wimbledon,1,0,H,0,...,1.93,1.93,1.93,1.95,1.98,1.93,1.91,1.82,1.94,2.01
1,E2,25,02/08/2025,12:30,Cardiff,Peterboro,2,1,H,0,...,1.85,2.00,1.87,2.03,1.90,2.00,1.85,1.88,1.93,2.04
2,E2,25,02/08/2025,15:00,Blackpool,Stevenage,2,3,A,1,...,1.93,1.93,1.94,1.94,1.94,1.93,1.84,1.87,1.94,2.04
3,E2,25,02/08/2025,15:00,Bradford,Wycombe,2,1,H,2,...,1.73,2.08,1.90,1.99,1.77,2.20,1.72,2.02,1.80,2.22
4,E2,25,02/08/2025,15:00,Burton,Mansfield,2,1,H,1,...,2.00,1.85,1.69,2.26,2.00,1.85,1.93,1.79,2.04,1.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E2,25,02/05/2026,15:00,Peterboro,Doncaster,1,3,A,0,...,2.05,1.80,NaN,NaN,2.05,1.80,1.99,1.75,NaN,NaN
548,E2,25,02/05/2026,15:00,Port Vale,Lincoln,0,2,A,0,...,1.98,1.88,NaN,NaN,1.98,1.90,1.91,1.82,NaN,NaN
549,E2,25,02/05/2026,15:00,Reading,Blackpool,0,1,A,0,...,2.03,1.83,NaN,NaN,2.03,1.83,1.94,1.78,NaN,NaN
550,E2,25,02/05/2026,15:00,Stevenage,Wigan,1,0,H,0,...,2.03,1.83,NaN,NaN,2.03,1.85,1.93,1.80,NaN,NaN
551,E2,25,02/05/2026,15:00,Wycombe,Rotherham,3,2,H,2,...,1.75,2.05,NaN,NaN,1.83,2.10,1.72,2.01,NaN,NaN

Organize all the data in a dictionary

In [16]:
#create a dictionary with original name of league as key
football_country_codes = {
    'Spanish La Liga':'SP1',
    'German Bundesliga':'D1',
    'English Premier League':'E0',
    'English League 1':'E2'
}


#create a root variable 
root = 'https://www.football-data.co.uk/mmz4281/'
dict_historic_data = {}


for league in football_country_codes:
    frames  = [] #list of dataframes
    for season in range(24,26):
        
        df = pd.read_csv(root + str(season) + str(season+1)  + '/' + football_country_codes[league] + '.csv' , encoding='unicode_escape')
        #add a new column indicating which season is in dataframe
        df.insert(1,'season', str(season))
        frames.append(df)
    #concatenate all seasons in 1 dataframe
    df_concat =  pd.concat(frames)
    #combine league name(key) with dataframe of all seasons(24-25) 
    dict_historic_data[league] = df_concat

In [18]:
dict_historic_data.keys()
dict_historic_data['Spanish La Liga']

,ï»¿Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,SP1,24,15/08/2024,18:00,Ath Bilbao,Getafe,1,1,D,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,24,15/08/2024,20:30,Betis,Girona,1,1,D,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,24,16/08/2024,18:00,Celta,Alaves,2,1,H,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,24,16/08/2024,20:30,Las Palmas,Sevilla,2,2,D,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,24,17/08/2024,18:00,Osasuna,Leganes,1,1,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,SP1,25,17/05/2026,18:00,Oviedo,Alaves,0,1,A,0,...,1.96,3.75,3.20,2.10,3.75,3.20,2.1,3.70,3.10,2.1
366,SP1,25,17/05/2026,18:00,Sevilla,Real Madrid,0,1,A,0,...,1.95,3.60,3.80,1.95,3.60,3.70,2.0,3.50,3.60,2.0
367,SP1,25,17/05/2026,18:00,Sociedad,Valencia,3,4,A,1,...,2.95,2.40,3.25,3.00,2.40,3.25,3.0,2.37,3.25,3.0
368,SP1,25,17/05/2026,18:00,Vallecano,Villarreal,2,0,H,1,...,3.40,1.95,3.70,3.60,1.95,3.60,3.7,1.95,3.60,3.7
369,SP1,25,17/05/2026,20:15,Barcelona,Betis,3,1,H,1,...,6.75,1.33,5.75,8.00,1.35,5.75,7.0,1.35,5.75,7.0