In [6]:
import pandas as pd

df_movies_org = pd.read_csv('IMDb movies.csv', low_memory=False)
df_ratings_org = pd.read_csv('IMDb ratings.csv', low_memory=False)

In [8]:
df_movies = df_movies_org[['imdb_title_id','title','year','genre','country']]

df_ratings = df_ratings_org[['imdb_title_id','total_votes','mean_vote']]

1 concat()
1.1 concatenate vertically

In [9]:


df1 = pd.DataFrame({'id':['A','B','C','D'] ,
                     'age':[30,23,25,22] })
df2 = pd.DataFrame({'id':['E','F','G','H'] ,
                     'age':[40,21,19,24] })

In [11]:
pd.concat([df1 , df2], axis = 0, ignore_index=True) #we want o concatenate vertically

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
4  E   40
5  F   21
6  G   19
7  H   24

1.1.1 Exercise

In [13]:
#extract a 50% sample of the original dataframe df_movies
df_movies_sample =  df_movies.sample(frac=0.5)

In [14]:
#shape of dataframe that we'll concatenate
df_movies_sample.shape

(42928, 5)

In [16]:
#concatenate df_movies and df_sample vertically

df_concat_movies = pd.concat([df_movies , df_movies_sample] , axis = 0, ignore_index=True)

In [17]:
df_concat_movies.shape

(128783, 5)

1.2 concatenate horizontally

In [19]:
df1 = pd.DataFrame({'id':['A','B','C','D'] ,
                     'age':[30,23,25,22] })
df2 = pd.DataFrame({'job':['doctor','statistician','accountant','developer'] })

In [20]:
pd.concat([df1,df2] , axis=1)

  id  age           job
0  A   30        doctor
1  B   23  statistician
2  C   25    accountant
3  D   22     developer

1.2.1 exercise

In [22]:
#shaoe of dataframe that we will concatenate
df_movies.shape
df_ratings.shape

(85855, 3)

In [24]:
#concatenate on imdb_title_id
df_ratings.set_index('imdb_title_id',inplace=True)
df_movies.set_index('imdb_title_id',inplace=True)

KeyError: "None of ['imdb_title_id'] are in the columns"

In [27]:
#concatenate on imdb_title_id
df_concat_horizontal  = pd.concat([df_movies, df_ratings], axis=1 )

In [26]:
#shape
df_concat_horizontal.shape

(85855, 6)

Joins 
1 Merge()

In [30]:
df1 = pd.DataFrame({'id':['A','B','C','D'] ,
                     'age':[30,23,25,22] })
df2 = pd.DataFrame({'id':['C','D','E','F'] , 
                    'job':['doctor','statistician','accountant','developer'] })

1.1 Inner join

In [32]:
df_inner_join = df1.merge(df2, on='id' , how='inner')
df_inner_join

  id  age           job
0  C   25        doctor
1  D   22  statistician

In [35]:
print(df1.shape)
print(df2.shape)
print(df_inner_join.shape)

(4, 2)
(4, 2)
(2, 3)

1.1.1 Exercise

In [36]:
#merge df_movies and df_raatings 

df_movies.merge(df_ratings , on='imdb_title_id' , how='inner')

,title,year,genre,country,total_votes,mean_vote
imdb_title_id,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

1.2 Outer join (Full join)

In [38]:
df1.merge(df2 , on='id' , how='outer')

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        doctor
3  D  22.0  statistician
4  E   NaN    accountant
5  F   NaN     developer

1.2.1 Exercise
#merge movies and ratings df outer join

In [39]:
df_movies.merge(df_ratings , on='imdb_title_id' , how='outer')

,title,year,genre,country,total_votes,mean_vote
imdb_title_id,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

Joins (Exclusive full join) - does not include common values between 2 df

In [40]:
df1.merge(df2 , on='id' , how='outer', indicator=True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        doctor        both
3  D  22.0  statistician        both
4  E   NaN    accountant  right_only
5  F   NaN     developer  right_only

In [41]:
df1.merge(df2 , on='id' , how='outer'
          , indicator=True).query('_merge=="left_only" or _merge=="right_only"')

  id   age         job      _merge
0  A  30.0         NaN   left_only
1  B  23.0         NaN   left_only
4  E   NaN  accountant  right_only
5  F   NaN   developer  right_only

1.3.1 Exercise

In [43]:
df_movies.merge(df_ratings , on='imdb_title_id' , how='outer' , indicator=True)

,title,year,genre,country,total_votes,mean_vote,_merge
imdb_title_id,,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,154,5.9,both
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3,both
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0,both
tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3,both
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9,both
...,...,...,...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5,both
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9,both
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8,both
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4,both
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8,both

In [44]:
df_movies.merge(df_ratings , on='imdb_title_id' , how='outer' , indicator=True).query('_merge=="left_only" or _merge=="right_only"')

Empty DataFrame
Columns: [title, year, genre, country, total_votes, mean_vote, _merge]
Index: []

1.4 Joins Left join - only gets data from left table

In [45]:
df1.merge(df2 , on='id' , how='left')

  id  age           job
0  A   30           NaN
1  B   23           NaN
2  C   25        doctor
3  D   22  statistician

1.5 Right join - only gets data from right table

In [46]:
df1.merge(df2 , on='id' , how='right')

  id   age           job
0  C  25.0        doctor
1  D  22.0  statistician
2  E   NaN    accountant
3  F   NaN     developer

1.6 Exclusive left join only - data is only picked from the first table and also which is not common with second table

In [47]:
df1.merge(df2 , on='id' , how='outer'
          , indicator=True).query('_merge=="left_only"')

  id   age  job     _merge
0  A  30.0  NaN  left_only
1  B  23.0  NaN  left_only

1.7 Exclusive right join only - data is only picked from the second table and also which is not common with first table

In [48]:
df1.merge(df2 , on='id' , how='outer'
          , indicator=True).query('_merge=="right_only"')

  id  age         job      _merge
4  E  NaN  accountant  right_only
5  F  NaN   developer  right_only