In [1]:
import pandas as pd

In [2]:
df_laptop = pd.read_csv('laptop_price.csv',encoding='unicode_escape')

1. create a column based on 1 condition:
np.where()

In [3]:
import numpy as np

In [6]:
# where > condition : yes : no
np.where( df_laptop['Price_euros'] > 2000 , 'Expensive', 'Cheap')

array(['Cheap', 'Cheap', 'Cheap', ..., 'Cheap', 'Cheap', 'Cheap'],
      shape=(1303,), dtype='<U9')

In [8]:
df_laptop['Price-tier'] = np.where( df_laptop['Price_euros'] > 2000 , 'Expensive', 'Cheap')

In [9]:
df_laptop.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price-tier
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Cheap
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Cheap

In [10]:
#count value in price-tier column
df_laptop.value_counts('Price-tier')

Price-tier
Cheap        1166
Expensive     137
Name: count, dtype: int64

1 Exercise create an array based on screen size

In [16]:
np.where(df_laptop['Inches'] > 15 , 'Large' ,'Mid Or Small')

array(['Mid Or Small', 'Mid Or Small', 'Large', ..., 'Mid Or Small',
       'Large', 'Large'], shape=(1303,), dtype='<U12')

In [17]:
df_laptop['Display_category'] = np.where(df_laptop['Inches'] > 15 , 'Large' ,'Mid Or Small')

In [19]:
df_laptop.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price-tier,Display_category
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Cheap,Mid Or Small
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap,Mid Or Small
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap,Large
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive,Large
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Cheap,Mid Or Small

In [20]:
df_laptop.value_counts('Display_category')

Display_category
Large           835
Mid Or Small    468
Name: count, dtype: int64